// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goshare/instrument.proto

package goshare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 品种类型
type ProductType int32

const (
	ProductType_UNKOWN_PRODUCT ProductType = 0
	ProductType_FUTURE         ProductType = 1
	ProductType_STOCK          ProductType = 2
	ProductType_BOND           ProductType = 3
	ProductType_COMBINATION    ProductType = 4
	ProductType_OPTION         ProductType = 5
	ProductType_FUTURE_OPTION  ProductType = 6
	ProductType_SPOT_OPTION    ProductType = 7
	ProductType_SSE_ETF_OPTION ProductType = 8
)

var ProductType_name = map[int32]string{
	0: "UNKOWN_PRODUCT",
	1: "FUTURE",
	2: "STOCK",
	3: "BOND",
	4: "COMBINATION",
	5: "OPTION",
	6: "FUTURE_OPTION",
	7: "SPOT_OPTION",
	8: "SSE_ETF_OPTION",
}

var ProductType_value = map[string]int32{
	"UNKOWN_PRODUCT": 0,
	"FUTURE":         1,
	"STOCK":          2,
	"BOND":           3,
	"COMBINATION":    4,
	"OPTION":         5,
	"FUTURE_OPTION":  6,
	"SPOT_OPTION":    7,
	"SSE_ETF_OPTION": 8,
}

func (x ProductType) String() string {
	return proto.EnumName(ProductType_name, int32(x))
}

func (ProductType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{0}
}

type CallPutType int32

const (
	CallPutType_CALL CallPutType = 0
	CallPutType_PUT  CallPutType = 1
)

var CallPutType_name = map[int32]string{
	0: "CALL",
	1: "PUT",
}

var CallPutType_value = map[string]int32{
	"CALL": 0,
	"PUT":  1,
}

func (x CallPutType) String() string {
	return proto.EnumName(CallPutType_name, int32(x))
}

func (CallPutType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{1}
}

// 合约组
type SymbolGroupType int32

const (
	SymbolGroupType_CTP_FUTURE_ALL      SymbolGroupType = 0
	SymbolGroupType_CTP_FUTURE_FUTURE   SymbolGroupType = 1
	SymbolGroupType_CTP_FUTURE_OPTION   SymbolGroupType = 2
	SymbolGroupType_CTP_FUTURE_COMBINE  SymbolGroupType = 3
	SymbolGroupType_CTP_SOPT_ALL        SymbolGroupType = 4
	SymbolGroupType_CTP_SOPT_ETF_OPTION SymbolGroupType = 5
	SymbolGroupType_CTP_SOPT_SSE_STOCK  SymbolGroupType = 6
	SymbolGroupType_CTP_SOPT_SZE_STOCK  SymbolGroupType = 7
)

var SymbolGroupType_name = map[int32]string{
	0: "CTP_FUTURE_ALL",
	1: "CTP_FUTURE_FUTURE",
	2: "CTP_FUTURE_OPTION",
	3: "CTP_FUTURE_COMBINE",
	4: "CTP_SOPT_ALL",
	5: "CTP_SOPT_ETF_OPTION",
	6: "CTP_SOPT_SSE_STOCK",
	7: "CTP_SOPT_SZE_STOCK",
}

var SymbolGroupType_value = map[string]int32{
	"CTP_FUTURE_ALL":      0,
	"CTP_FUTURE_FUTURE":   1,
	"CTP_FUTURE_OPTION":   2,
	"CTP_FUTURE_COMBINE":  3,
	"CTP_SOPT_ALL":        4,
	"CTP_SOPT_ETF_OPTION": 5,
	"CTP_SOPT_SSE_STOCK":  6,
	"CTP_SOPT_SZE_STOCK":  7,
}

func (x SymbolGroupType) String() string {
	return proto.EnumName(SymbolGroupType_name, int32(x))
}

func (SymbolGroupType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{2}
}

// 市场状态
type MarketStatus struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time"`
	Send                 bool     `protobuf:"varint,2,opt,name=send,proto3" json:"send"`
	Cancel               bool     `protobuf:"varint,3,opt,name=cancel,proto3" json:"cancel"`
	Matching             bool     `protobuf:"varint,4,opt,name=matching,proto3" json:"matching"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MarketStatus) Reset()         { *m = MarketStatus{} }
func (m *MarketStatus) String() string { return proto.CompactTextString(m) }
func (*MarketStatus) ProtoMessage()    {}
func (*MarketStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{0}
}

func (m *MarketStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MarketStatus.Unmarshal(m, b)
}
func (m *MarketStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MarketStatus.Marshal(b, m, deterministic)
}
func (m *MarketStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MarketStatus.Merge(m, src)
}
func (m *MarketStatus) XXX_Size() int {
	return xxx_messageInfo_MarketStatus.Size(m)
}
func (m *MarketStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MarketStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MarketStatus proto.InternalMessageInfo

func (m *MarketStatus) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MarketStatus) GetSend() bool {
	if m != nil {
		return m.Send
	}
	return false
}

func (m *MarketStatus) GetCancel() bool {
	if m != nil {
		return m.Cancel
	}
	return false
}

func (m *MarketStatus) GetMatching() bool {
	if m != nil {
		return m.Matching
	}
	return false
}

// 合约属性
type Instrument struct {
	Exchange                    string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol                      string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Product                     string          `protobuf:"bytes,3,opt,name=product,proto3" json:"product"`
	Multiple                    int32           `protobuf:"varint,4,opt,name=multiple,proto3" json:"multiple"`
	PriceTick                   float64         `protobuf:"fixed64,5,opt,name=price_tick,json=priceTick,proto3" json:"priceTick"`
	Name                        string          `protobuf:"bytes,6,opt,name=name,proto3" json:"name"`
	PositionRank                int32           `protobuf:"varint,7,opt,name=position_rank,json=positionRank,proto3" json:"positionRank"`
	UpdateTime                  int64           `protobuf:"varint,8,opt,name=update_time,json=updateTime,proto3" json:"updateTime"`
	TradingDay                  int32           `protobuf:"varint,9,opt,name=trading_day,json=tradingDay,proto3" json:"tradingDay"`
	UpperLimit                  float64         `protobuf:"fixed64,10,opt,name=upper_limit,json=upperLimit,proto3" json:"upperLimit"`
	LowerLimit                  float64         `protobuf:"fixed64,11,opt,name=lower_limit,json=lowerLimit,proto3" json:"lowerLimit"`
	PreClose                    float64         `protobuf:"fixed64,12,opt,name=pre_close,json=preClose,proto3" json:"preClose"`
	PreSettlement               float64         `protobuf:"fixed64,13,opt,name=pre_settlement,json=preSettlement,proto3" json:"preSettlement"`
	PreVolume                   int32           `protobuf:"varint,14,opt,name=pre_volume,json=preVolume,proto3" json:"preVolume"`
	PrePosition                 int32           `protobuf:"varint,15,opt,name=pre_position,json=prePosition,proto3" json:"prePosition"`
	SettlementPrice             float64         `protobuf:"fixed64,16,opt,name=settlement_price,json=settlementPrice,proto3" json:"settlementPrice"`
	CreateDate                  int32           `protobuf:"varint,17,opt,name=create_date,json=createDate,proto3" json:"createDate"`
	OpenDate                    int32           `protobuf:"varint,18,opt,name=open_date,json=openDate,proto3" json:"openDate"`
	ExpireDate                  int32           `protobuf:"varint,19,opt,name=expire_date,json=expireDate,proto3" json:"expireDate"`
	StartDeliverDate            int32           `protobuf:"varint,20,opt,name=start_deliver_date,json=startDeliverDate,proto3" json:"startDeliverDate"`
	EndDeliverDate              int32           `protobuf:"varint,21,opt,name=end_deliver_date,json=endDeliverDate,proto3" json:"endDeliverDate"`
	IsCloseTodayAllowed         bool            `protobuf:"varint,22,opt,name=is_close_today_allowed,json=isCloseTodayAllowed,proto3" json:"isCloseTodayAllowed"`
	MaxMarketOrderVolume        int32           `protobuf:"varint,23,opt,name=max_market_order_volume,json=maxMarketOrderVolume,proto3" json:"maxMarketOrderVolume"`
	MinMarketOrderVolume        int32           `protobuf:"varint,24,opt,name=min_market_order_volume,json=minMarketOrderVolume,proto3" json:"minMarketOrderVolume"`
	MaxLimitOrderVolume         int32           `protobuf:"varint,25,opt,name=max_limit_order_volume,json=maxLimitOrderVolume,proto3" json:"maxLimitOrderVolume"`
	MinLimitOrderVolume         int32           `protobuf:"varint,26,opt,name=min_limit_order_volume,json=minLimitOrderVolume,proto3" json:"minLimitOrderVolume"`
	UnderlyingSymbol            string          `protobuf:"bytes,27,opt,name=underlying_symbol,json=underlyingSymbol,proto3" json:"underlyingSymbol"`
	StrikePrice                 float64         `protobuf:"fixed64,28,opt,name=strike_price,json=strikePrice,proto3" json:"strikePrice"`
	CallOrPut                   string          `protobuf:"bytes,29,opt,name=call_or_put,json=callOrPut,proto3" json:"callOrPut"`
	UnderlyingMultiple          float64         `protobuf:"fixed64,30,opt,name=underlying_multiple,json=underlyingMultiple,proto3" json:"underlyingMultiple"`
	MinBuyVolume                int32           `protobuf:"varint,31,opt,name=min_buy_volume,json=minBuyVolume,proto3" json:"minBuyVolume"`
	MinSellVolume               int32           `protobuf:"varint,32,opt,name=min_sell_volume,json=minSellVolume,proto3" json:"minSellVolume"`
	IsTrading                   bool            `protobuf:"varint,33,opt,name=is_trading,json=isTrading,proto3" json:"isTrading"`
	ExerciseDateType            string          `protobuf:"bytes,34,opt,name=exercise_date_type,json=exerciseDateType,proto3" json:"exerciseDateType"`
	ProductName                 string          `protobuf:"bytes,35,opt,name=product_name,json=productName,proto3" json:"productName"`
	ProductType                 int32           `protobuf:"varint,36,opt,name=product_type,json=productType,proto3" json:"productType"`
	ProductClass                string          `protobuf:"bytes,37,opt,name=product_class,json=productClass,proto3" json:"productClass"`
	DistinguishPositionTimeType bool            `protobuf:"varint,38,opt,name=distinguish_position_time_type,json=distinguishPositionTimeType,proto3" json:"distinguishPositionTimeType"`
	TimeRule                    []*MarketStatus `protobuf:"bytes,39,rep,name=time_rule,json=timeRule,proto3" json:"timeRule"`
	LeftDays                    int32           `protobuf:"varint,40,opt,name=left_days,json=leftDays,proto3" json:"leftDays"`
	MonthGroup                  string          `protobuf:"bytes,41,opt,name=month_group,json=monthGroup,proto3" json:"monthGroup"`
	CallPutType                 CallPutType     `protobuf:"varint,42,opt,name=call_put_type,json=callPutType,proto3,enum=goshare.CallPutType" json:"callPutType"`
	XXX_NoUnkeyedLiteral        struct{}        `json:"-"`
	XXX_unrecognized            []byte          `json:"-"`
	XXX_sizecache               int32           `json:"-"`
}

func (m *Instrument) Reset()         { *m = Instrument{} }
func (m *Instrument) String() string { return proto.CompactTextString(m) }
func (*Instrument) ProtoMessage()    {}
func (*Instrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{1}
}

func (m *Instrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Instrument.Unmarshal(m, b)
}
func (m *Instrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Instrument.Marshal(b, m, deterministic)
}
func (m *Instrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Instrument.Merge(m, src)
}
func (m *Instrument) XXX_Size() int {
	return xxx_messageInfo_Instrument.Size(m)
}
func (m *Instrument) XXX_DiscardUnknown() {
	xxx_messageInfo_Instrument.DiscardUnknown(m)
}

var xxx_messageInfo_Instrument proto.InternalMessageInfo

func (m *Instrument) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Instrument) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Instrument) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Instrument) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *Instrument) GetPriceTick() float64 {
	if m != nil {
		return m.PriceTick
	}
	return 0
}

func (m *Instrument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Instrument) GetPositionRank() int32 {
	if m != nil {
		return m.PositionRank
	}
	return 0
}

func (m *Instrument) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Instrument) GetTradingDay() int32 {
	if m != nil {
		return m.TradingDay
	}
	return 0
}

func (m *Instrument) GetUpperLimit() float64 {
	if m != nil {
		return m.UpperLimit
	}
	return 0
}

func (m *Instrument) GetLowerLimit() float64 {
	if m != nil {
		return m.LowerLimit
	}
	return 0
}

func (m *Instrument) GetPreClose() float64 {
	if m != nil {
		return m.PreClose
	}
	return 0
}

func (m *Instrument) GetPreSettlement() float64 {
	if m != nil {
		return m.PreSettlement
	}
	return 0
}

func (m *Instrument) GetPreVolume() int32 {
	if m != nil {
		return m.PreVolume
	}
	return 0
}

func (m *Instrument) GetPrePosition() int32 {
	if m != nil {
		return m.PrePosition
	}
	return 0
}

func (m *Instrument) GetSettlementPrice() float64 {
	if m != nil {
		return m.SettlementPrice
	}
	return 0
}

func (m *Instrument) GetCreateDate() int32 {
	if m != nil {
		return m.CreateDate
	}
	return 0
}

func (m *Instrument) GetOpenDate() int32 {
	if m != nil {
		return m.OpenDate
	}
	return 0
}

func (m *Instrument) GetExpireDate() int32 {
	if m != nil {
		return m.ExpireDate
	}
	return 0
}

func (m *Instrument) GetStartDeliverDate() int32 {
	if m != nil {
		return m.StartDeliverDate
	}
	return 0
}

func (m *Instrument) GetEndDeliverDate() int32 {
	if m != nil {
		return m.EndDeliverDate
	}
	return 0
}

func (m *Instrument) GetIsCloseTodayAllowed() bool {
	if m != nil {
		return m.IsCloseTodayAllowed
	}
	return false
}

func (m *Instrument) GetMaxMarketOrderVolume() int32 {
	if m != nil {
		return m.MaxMarketOrderVolume
	}
	return 0
}

func (m *Instrument) GetMinMarketOrderVolume() int32 {
	if m != nil {
		return m.MinMarketOrderVolume
	}
	return 0
}

func (m *Instrument) GetMaxLimitOrderVolume() int32 {
	if m != nil {
		return m.MaxLimitOrderVolume
	}
	return 0
}

func (m *Instrument) GetMinLimitOrderVolume() int32 {
	if m != nil {
		return m.MinLimitOrderVolume
	}
	return 0
}

func (m *Instrument) GetUnderlyingSymbol() string {
	if m != nil {
		return m.UnderlyingSymbol
	}
	return ""
}

func (m *Instrument) GetStrikePrice() float64 {
	if m != nil {
		return m.StrikePrice
	}
	return 0
}

func (m *Instrument) GetCallOrPut() string {
	if m != nil {
		return m.CallOrPut
	}
	return ""
}

func (m *Instrument) GetUnderlyingMultiple() float64 {
	if m != nil {
		return m.UnderlyingMultiple
	}
	return 0
}

func (m *Instrument) GetMinBuyVolume() int32 {
	if m != nil {
		return m.MinBuyVolume
	}
	return 0
}

func (m *Instrument) GetMinSellVolume() int32 {
	if m != nil {
		return m.MinSellVolume
	}
	return 0
}

func (m *Instrument) GetIsTrading() bool {
	if m != nil {
		return m.IsTrading
	}
	return false
}

func (m *Instrument) GetExerciseDateType() string {
	if m != nil {
		return m.ExerciseDateType
	}
	return ""
}

func (m *Instrument) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *Instrument) GetProductType() int32 {
	if m != nil {
		return m.ProductType
	}
	return 0
}

func (m *Instrument) GetProductClass() string {
	if m != nil {
		return m.ProductClass
	}
	return ""
}

func (m *Instrument) GetDistinguishPositionTimeType() bool {
	if m != nil {
		return m.DistinguishPositionTimeType
	}
	return false
}

func (m *Instrument) GetTimeRule() []*MarketStatus {
	if m != nil {
		return m.TimeRule
	}
	return nil
}

func (m *Instrument) GetLeftDays() int32 {
	if m != nil {
		return m.LeftDays
	}
	return 0
}

func (m *Instrument) GetMonthGroup() string {
	if m != nil {
		return m.MonthGroup
	}
	return ""
}

func (m *Instrument) GetCallPutType() CallPutType {
	if m != nil {
		return m.CallPutType
	}
	return CallPutType_CALL
}

// 合约列表
type InstrumentList struct {
	List                 []*Instrument `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *InstrumentList) Reset()         { *m = InstrumentList{} }
func (m *InstrumentList) String() string { return proto.CompactTextString(m) }
func (*InstrumentList) ProtoMessage()    {}
func (*InstrumentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{2}
}

func (m *InstrumentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InstrumentList.Unmarshal(m, b)
}
func (m *InstrumentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InstrumentList.Marshal(b, m, deterministic)
}
func (m *InstrumentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InstrumentList.Merge(m, src)
}
func (m *InstrumentList) XXX_Size() int {
	return xxx_messageInfo_InstrumentList.Size(m)
}
func (m *InstrumentList) XXX_DiscardUnknown() {
	xxx_messageInfo_InstrumentList.DiscardUnknown(m)
}

var xxx_messageInfo_InstrumentList proto.InternalMessageInfo

func (m *InstrumentList) GetList() []*Instrument {
	if m != nil {
		return m.List
	}
	return nil
}

// 期权按月分组
type OptionMonthGroup struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Product              string   `protobuf:"bytes,2,opt,name=product,proto3" json:"product"`
	Strike               string   `protobuf:"bytes,3,opt,name=strike,proto3" json:"strike"`
	MonthGroup           string   `protobuf:"bytes,4,opt,name=month_group,json=monthGroup,proto3" json:"monthGroup"`
	LeftDays             int32    `protobuf:"varint,5,opt,name=left_days,json=leftDays,proto3" json:"leftDays"`
	ProductName          string   `protobuf:"bytes,6,opt,name=product_name,json=productName,proto3" json:"productName"`
	Instruments          []string `protobuf:"bytes,7,rep,name=instruments,proto3" json:"instruments"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptionMonthGroup) Reset()         { *m = OptionMonthGroup{} }
func (m *OptionMonthGroup) String() string { return proto.CompactTextString(m) }
func (*OptionMonthGroup) ProtoMessage()    {}
func (*OptionMonthGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{3}
}

func (m *OptionMonthGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionMonthGroup.Unmarshal(m, b)
}
func (m *OptionMonthGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionMonthGroup.Marshal(b, m, deterministic)
}
func (m *OptionMonthGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionMonthGroup.Merge(m, src)
}
func (m *OptionMonthGroup) XXX_Size() int {
	return xxx_messageInfo_OptionMonthGroup.Size(m)
}
func (m *OptionMonthGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionMonthGroup.DiscardUnknown(m)
}

var xxx_messageInfo_OptionMonthGroup proto.InternalMessageInfo

func (m *OptionMonthGroup) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OptionMonthGroup) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *OptionMonthGroup) GetStrike() string {
	if m != nil {
		return m.Strike
	}
	return ""
}

func (m *OptionMonthGroup) GetMonthGroup() string {
	if m != nil {
		return m.MonthGroup
	}
	return ""
}

func (m *OptionMonthGroup) GetLeftDays() int32 {
	if m != nil {
		return m.LeftDays
	}
	return 0
}

func (m *OptionMonthGroup) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func (m *OptionMonthGroup) GetInstruments() []string {
	if m != nil {
		return m.Instruments
	}
	return nil
}

// 期权组列表
type OptionMonthGroupList struct {
	Exchange             string              `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Product              string              `protobuf:"bytes,2,opt,name=product,proto3" json:"product"`
	List                 []*OptionMonthGroup `protobuf:"bytes,3,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *OptionMonthGroupList) Reset()         { *m = OptionMonthGroupList{} }
func (m *OptionMonthGroupList) String() string { return proto.CompactTextString(m) }
func (*OptionMonthGroupList) ProtoMessage()    {}
func (*OptionMonthGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{4}
}

func (m *OptionMonthGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptionMonthGroupList.Unmarshal(m, b)
}
func (m *OptionMonthGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptionMonthGroupList.Marshal(b, m, deterministic)
}
func (m *OptionMonthGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionMonthGroupList.Merge(m, src)
}
func (m *OptionMonthGroupList) XXX_Size() int {
	return xxx_messageInfo_OptionMonthGroupList.Size(m)
}
func (m *OptionMonthGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionMonthGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_OptionMonthGroupList proto.InternalMessageInfo

func (m *OptionMonthGroupList) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *OptionMonthGroupList) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *OptionMonthGroupList) GetList() []*OptionMonthGroup {
	if m != nil {
		return m.List
	}
	return nil
}

// 合约
type UniqueSymbol struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UniqueSymbol) Reset()         { *m = UniqueSymbol{} }
func (m *UniqueSymbol) String() string { return proto.CompactTextString(m) }
func (*UniqueSymbol) ProtoMessage()    {}
func (*UniqueSymbol) Descriptor() ([]byte, []int) {
	return fileDescriptor_faf3e5650851e9a9, []int{5}
}

func (m *UniqueSymbol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UniqueSymbol.Unmarshal(m, b)
}
func (m *UniqueSymbol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UniqueSymbol.Marshal(b, m, deterministic)
}
func (m *UniqueSymbol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UniqueSymbol.Merge(m, src)
}
func (m *UniqueSymbol) XXX_Size() int {
	return xxx_messageInfo_UniqueSymbol.Size(m)
}
func (m *UniqueSymbol) XXX_DiscardUnknown() {
	xxx_messageInfo_UniqueSymbol.DiscardUnknown(m)
}

var xxx_messageInfo_UniqueSymbol proto.InternalMessageInfo

func (m *UniqueSymbol) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *UniqueSymbol) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func init() {
	proto.RegisterEnum("goshare.ProductType", ProductType_name, ProductType_value)
	proto.RegisterEnum("goshare.CallPutType", CallPutType_name, CallPutType_value)
	proto.RegisterEnum("goshare.SymbolGroupType", SymbolGroupType_name, SymbolGroupType_value)
	proto.RegisterType((*MarketStatus)(nil), "goshare.MarketStatus")
	proto.RegisterType((*Instrument)(nil), "goshare.Instrument")
	proto.RegisterType((*InstrumentList)(nil), "goshare.InstrumentList")
	proto.RegisterType((*OptionMonthGroup)(nil), "goshare.OptionMonthGroup")
	proto.RegisterType((*OptionMonthGroupList)(nil), "goshare.OptionMonthGroupList")
	proto.RegisterType((*UniqueSymbol)(nil), "goshare.UniqueSymbol")
}

func init() { proto.RegisterFile("goshare/instrument.proto", fileDescriptor_faf3e5650851e9a9) }

var fileDescriptor_faf3e5650851e9a9 = []byte{
	// 1258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xdb, 0x6e, 0x1b, 0x37,
	0x13, 0x8e, 0x2c, 0x5b, 0x87, 0x91, 0x2c, 0xaf, 0x69, 0xc7, 0x61, 0x92, 0x3f, 0xb1, 0xe2, 0x9c,
	0x14, 0xe7, 0x8f, 0x05, 0x24, 0x28, 0xd0, 0x5e, 0xc6, 0xb2, 0x53, 0x04, 0xb1, 0x2d, 0x61, 0xb5,
	0x6e, 0x81, 0xdc, 0x2c, 0xd6, 0x2b, 0x56, 0x66, 0xbd, 0xa7, 0x92, 0xdc, 0xd4, 0x42, 0x1f, 0xa4,
	0x6f, 0xd4, 0xd7, 0xe8, 0x45, 0x5f, 0xa4, 0xe0, 0x90, 0xbb, 0x92, 0xec, 0xa0, 0x17, 0xb9, 0x5b,
	0x7e, 0xf3, 0xcd, 0x0c, 0xe7, 0xd3, 0x0c, 0x47, 0x40, 0xa7, 0xa9, 0xbc, 0x0c, 0x04, 0xeb, 0xf3,
	0x44, 0x2a, 0x91, 0xc7, 0x2c, 0x51, 0x07, 0x99, 0x48, 0x55, 0x4a, 0xea, 0xd6, 0xb2, 0xf7, 0x2b,
	0xb4, 0x4f, 0x03, 0x71, 0xc5, 0xd4, 0x58, 0x05, 0x2a, 0x97, 0x84, 0xc0, 0xaa, 0xe2, 0x31, 0xa3,
	0x95, 0x6e, 0xa5, 0x57, 0x75, 0xf1, 0x5b, 0x63, 0x92, 0x25, 0x13, 0xba, 0xd2, 0xad, 0xf4, 0x1a,
	0x2e, 0x7e, 0x93, 0x1d, 0xa8, 0x85, 0x41, 0x12, 0xb2, 0x88, 0x56, 0x11, 0xb5, 0x27, 0xf2, 0x00,
	0x1a, 0x71, 0xa0, 0xc2, 0x4b, 0x9e, 0x4c, 0xe9, 0x2a, 0x5a, 0xca, 0xf3, 0xde, 0xdf, 0x6d, 0x80,
	0x8f, 0xe5, 0x4d, 0x34, 0x95, 0x5d, 0x87, 0x97, 0x41, 0x32, 0x35, 0xe9, 0x9a, 0x6e, 0x79, 0xd6,
	0xe1, 0xe5, 0x2c, 0xbe, 0x48, 0x23, 0x4c, 0xda, 0x74, 0xed, 0x89, 0x50, 0xa8, 0x67, 0x22, 0x9d,
	0xe4, 0xa1, 0xc2, 0xbc, 0x4d, 0xb7, 0x38, 0x62, 0xe2, 0x3c, 0x52, 0x3c, 0x8b, 0x18, 0x26, 0x5e,
	0x73, 0xcb, 0x33, 0x79, 0x04, 0x90, 0x09, 0x1e, 0x32, 0x5f, 0xf1, 0xf0, 0x8a, 0xae, 0x75, 0x2b,
	0xbd, 0x8a, 0xdb, 0x44, 0xc4, 0xe3, 0xe1, 0x95, 0xae, 0x2f, 0x09, 0x62, 0x46, 0x6b, 0x18, 0x11,
	0xbf, 0xc9, 0x53, 0x58, 0xcf, 0x52, 0xc9, 0x15, 0x4f, 0x13, 0x5f, 0x04, 0xc9, 0x15, 0xad, 0x63,
	0xcc, 0x76, 0x01, 0xba, 0x41, 0x72, 0x45, 0x76, 0xa1, 0x95, 0x67, 0x93, 0x40, 0xe9, 0xc0, 0x31,
	0xa3, 0x0d, 0xd4, 0x0c, 0x0c, 0xe4, 0x69, 0xe5, 0x76, 0xa1, 0xa5, 0x44, 0x30, 0xe1, 0xc9, 0xd4,
	0x9f, 0x04, 0x33, 0xda, 0xc4, 0x18, 0x60, 0xa1, 0xa3, 0x60, 0x66, 0x22, 0x64, 0x4c, 0xf8, 0x11,
	0x8f, 0xb9, 0xa2, 0x80, 0x57, 0x03, 0x84, 0x4e, 0x34, 0xa2, 0x09, 0x51, 0xfa, 0x7b, 0x49, 0x68,
	0x19, 0x02, 0x42, 0x86, 0xf0, 0x10, 0x9a, 0x99, 0x60, 0x7e, 0x18, 0xa5, 0x92, 0xd1, 0x36, 0x9a,
	0x1b, 0x99, 0x60, 0x03, 0x7d, 0x26, 0xcf, 0xa1, 0xa3, 0x8d, 0x92, 0x29, 0x15, 0x31, 0x2d, 0x3a,
	0x5d, 0x47, 0xc6, 0x7a, 0x26, 0xd8, 0xb8, 0x04, 0x8d, 0x3e, 0xcc, 0xff, 0x92, 0x46, 0x79, 0xcc,
	0x68, 0x07, 0x6f, 0xa9, 0xa3, 0xfe, 0x84, 0x00, 0x79, 0x02, 0x6d, 0x6d, 0x2e, 0x4a, 0xa7, 0x1b,
	0x48, 0x68, 0x65, 0x82, 0x8d, 0x2c, 0x44, 0x5e, 0x81, 0x33, 0x4f, 0xe2, 0xa3, 0xb4, 0xd4, 0xc1,
	0x54, 0x1b, 0x73, 0x7c, 0xa4, 0x61, 0x5d, 0x51, 0x28, 0x98, 0x16, 0x4d, 0xcb, 0x44, 0x37, 0x8d,
	0x26, 0x06, 0x3a, 0x0a, 0x14, 0xd3, 0x15, 0xa5, 0x19, 0x4b, 0x8c, 0x99, 0x98, 0x9f, 0x52, 0x03,
	0x68, 0xdc, 0x85, 0x16, 0xbb, 0xce, 0xb8, 0xb0, 0xde, 0x5b, 0xc6, 0xdb, 0x40, 0x48, 0xf8, 0x3f,
	0x10, 0xa9, 0x02, 0xa1, 0xfc, 0x09, 0x8b, 0xf8, 0x17, 0x26, 0x0c, 0x6f, 0x1b, 0x79, 0x0e, 0x5a,
	0x8e, 0x8c, 0x01, 0xd9, 0x3d, 0x70, 0x58, 0x32, 0x59, 0xe6, 0xde, 0x45, 0x6e, 0x87, 0x25, 0x93,
	0x45, 0xe6, 0x3b, 0xd8, 0xe1, 0xd2, 0xc8, 0xec, 0xab, 0x74, 0x12, 0xcc, 0xfc, 0x20, 0xd2, 0x3f,
	0xc3, 0x84, 0xee, 0x60, 0x9b, 0x6f, 0x71, 0x89, 0x9a, 0x7b, 0xda, 0xf6, 0xde, 0x98, 0xc8, 0x77,
	0x70, 0x2f, 0x0e, 0xae, 0xfd, 0x18, 0x27, 0xcc, 0x4f, 0xc5, 0x84, 0x89, 0x42, 0xe5, 0x7b, 0x98,
	0x65, 0x3b, 0x0e, 0xae, 0xcd, 0xfc, 0x0d, 0xb5, 0xd1, 0x0a, 0xae, 0xdd, 0x78, 0xf2, 0x55, 0x37,
	0x6a, 0xdd, 0x78, 0x72, 0xdb, 0xed, 0x1d, 0xec, 0xe8, 0x6c, 0xd8, 0x29, 0xcb, 0x5e, 0xf7, 0xd1,
	0x6b, 0x2b, 0x0e, 0xae, 0xb1, 0x69, 0x6e, 0x3a, 0xf1, 0xe4, 0x6b, 0x4e, 0x0f, 0xac, 0x13, 0x4f,
	0x6e, 0x39, 0xbd, 0x86, 0xcd, 0x3c, 0x99, 0x30, 0x11, 0xcd, 0x74, 0x6b, 0xdb, 0x49, 0x7d, 0x88,
	0xe3, 0xe3, 0xcc, 0x0d, 0x63, 0x33, 0xb3, 0x4f, 0xa0, 0x2d, 0x95, 0xe0, 0x57, 0xcc, 0xf6, 0xc5,
	0xff, 0xb0, 0x2f, 0x5a, 0x06, 0x33, 0x3d, 0xf1, 0x18, 0x5a, 0x61, 0x10, 0x45, 0x7e, 0x2a, 0xfc,
	0x2c, 0x57, 0xf4, 0x11, 0x46, 0x6a, 0x6a, 0x68, 0x28, 0x46, 0xb9, 0x22, 0x7d, 0xd8, 0x5a, 0xc8,
	0x57, 0xce, 0xf9, 0x63, 0x8c, 0x44, 0xe6, 0xa6, 0xd3, 0x62, 0xe2, 0x9f, 0x41, 0x47, 0x57, 0x75,
	0x91, 0xcf, 0x8a, 0x6a, 0x76, 0xcd, 0xfc, 0xc6, 0x3c, 0x39, 0xcc, 0x67, 0xb6, 0x8c, 0x17, 0xb0,
	0xa1, 0x59, 0x92, 0x45, 0x51, 0x41, 0xeb, 0x22, 0x6d, 0x3d, 0xe6, 0xc9, 0x98, 0x45, 0x91, 0xe5,
	0x3d, 0x02, 0xe0, 0xd2, 0xb7, 0x63, 0x4b, 0x9f, 0xe0, 0xef, 0xdd, 0xe4, 0xd2, 0x33, 0x80, 0x6e,
	0x39, 0x76, 0xcd, 0x44, 0xc8, 0xa5, 0xe9, 0x4a, 0x5f, 0xcd, 0x32, 0x46, 0xf7, 0x8c, 0x1c, 0x85,
	0x45, 0x37, 0x91, 0x37, 0xcb, 0xec, 0x34, 0xe1, 0x9b, 0xe5, 0xe3, 0xab, 0xf3, 0x14, 0x79, 0x2d,
	0x8b, 0x9d, 0x05, 0xf1, 0x12, 0x05, 0x43, 0x3d, 0x2b, 0x06, 0x0e, 0x31, 0x8c, 0xa2, 0xdf, 0x27,
	0x4b, 0x09, 0xa3, 0x40, 0x4a, 0xfa, 0x1c, 0xc3, 0x14, 0x7e, 0x03, 0x8d, 0x91, 0x01, 0x3c, 0x9e,
	0x70, 0xa9, 0x78, 0x32, 0xcd, 0xb9, 0xbc, 0x2c, 0x07, 0x18, 0x5f, 0x2b, 0x13, 0xf9, 0x05, 0xd6,
	0xf2, 0x70, 0x81, 0x55, 0x8c, 0xb4, 0x7e, 0xbf, 0x30, 0xd3, 0x5b, 0x68, 0x22, 0x5f, 0xe4, 0x11,
	0xa3, 0x2f, 0xbb, 0xd5, 0x5e, 0xeb, 0xed, 0xdd, 0x03, 0xbb, 0x3e, 0x0e, 0x16, 0x77, 0x87, 0xdb,
	0xd0, 0x3c, 0x37, 0x8f, 0x70, 0x84, 0x23, 0xf6, 0x8b, 0xd2, 0x8f, 0x9e, 0xa4, 0x3d, 0x33, 0xc2,
	0x1a, 0x38, 0x0a, 0x66, 0x52, 0x8f, 0x70, 0x9c, 0x26, 0xea, 0xd2, 0x9f, 0x8a, 0x34, 0xcf, 0xe8,
	0x2b, 0xbc, 0x38, 0x20, 0xf4, 0xa3, 0x46, 0xc8, 0xf7, 0xb0, 0x8e, 0xdd, 0x90, 0xe5, 0xb6, 0xfe,
	0xfd, 0x6e, 0xa5, 0xd7, 0x79, 0xbb, 0x5d, 0x66, 0x1d, 0x04, 0x51, 0x34, 0xca, 0x51, 0x08, 0x17,
	0x1b, 0xc7, 0x1e, 0xf6, 0x7e, 0x80, 0xce, 0x7c, 0xc1, 0x9c, 0x70, 0xa9, 0xc8, 0x4b, 0x58, 0x8d,
	0xb8, 0x54, 0xb4, 0x82, 0x17, 0xdf, 0x2a, 0x43, 0xcc, 0x69, 0x2e, 0x12, 0xf6, 0xfe, 0xa9, 0x80,
	0x33, 0xcc, 0x74, 0xe5, 0xa7, 0xf3, 0x9b, 0xfc, 0xd7, 0x8a, 0x5a, 0x58, 0x45, 0x2b, 0xcb, 0xab,
	0x48, 0x2f, 0x2f, 0x6c, 0x6e, 0xbb, 0xa3, 0xec, 0xe9, 0x66, 0xe1, 0xab, 0xb7, 0x0a, 0x5f, 0x92,
	0x6d, 0xed, 0x86, 0x6c, 0x37, 0xfb, 0xa6, 0x76, 0xbb, 0x6f, 0xba, 0xd0, 0x9a, 0x6f, 0x7a, 0x49,
	0xeb, 0xdd, 0xaa, 0x66, 0x2c, 0x40, 0x7b, 0x7f, 0xc0, 0xf6, 0xcd, 0x22, 0x51, 0xa6, 0x6f, 0x2b,
	0xf4, 0x8d, 0x15, 0xb7, 0x8a, 0xe2, 0xde, 0x2f, 0xc5, 0xbd, 0x99, 0xc2, 0x4a, 0x7c, 0x08, 0xed,
	0xf3, 0x84, 0xff, 0x96, 0x33, 0xfb, 0x30, 0x7c, 0xc3, 0x1f, 0x80, 0xfd, 0x3f, 0x2b, 0xd0, 0x1a,
	0x2d, 0xcc, 0x01, 0x81, 0xce, 0xf9, 0xd9, 0xa7, 0xe1, 0xcf, 0x67, 0xfe, 0xc8, 0x1d, 0x1e, 0x9d,
	0x0f, 0x3c, 0xe7, 0x0e, 0x01, 0xa8, 0x7d, 0x38, 0xf7, 0xce, 0xdd, 0x63, 0xa7, 0x42, 0x9a, 0xb0,
	0x36, 0xf6, 0x86, 0x83, 0x4f, 0xce, 0x0a, 0x69, 0xc0, 0xea, 0xe1, 0xf0, 0xec, 0xc8, 0xa9, 0x92,
	0x0d, 0x68, 0x0d, 0x86, 0xa7, 0x87, 0x1f, 0xcf, 0xde, 0x7b, 0x1f, 0x87, 0x67, 0xce, 0xaa, 0xf6,
	0x18, 0x8e, 0xf0, 0x7b, 0x8d, 0x6c, 0xc2, 0xba, 0xf1, 0xf6, 0x2d, 0x54, 0xd3, 0xfc, 0xf1, 0x68,
	0xe8, 0x15, 0x40, 0x5d, 0x67, 0x1d, 0x8f, 0x8f, 0xfd, 0x63, 0xef, 0x43, 0x81, 0x35, 0xf6, 0xbb,
	0xd0, 0x5a, 0xe8, 0x4b, 0x9d, 0x6d, 0xf0, 0xfe, 0xe4, 0xc4, 0xb9, 0x43, 0xea, 0x50, 0x1d, 0x9d,
	0x7b, 0x4e, 0x65, 0xff, 0xaf, 0x0a, 0x6c, 0x98, 0xd2, 0x51, 0x95, 0xe2, 0xfe, 0x03, 0x6f, 0xe4,
	0xdb, 0x8c, 0xc6, 0xe1, 0x2e, 0x6c, 0x2e, 0x60, 0x65, 0x29, 0xcb, 0xb0, 0xcd, 0xbb, 0x42, 0x76,
	0x80, 0x2c, 0xc0, 0xa6, 0xae, 0x63, 0xa7, 0x4a, 0x1c, 0x68, 0x6b, 0x7c, 0x3c, 0x1c, 0x79, 0x18,
	0x77, 0x95, 0xdc, 0x83, 0xad, 0x12, 0x59, 0xb8, 0xfa, 0x5a, 0x11, 0x02, 0x0d, 0xba, 0x2e, 0xa3,
	0x58, 0x6d, 0x19, 0xff, 0x5c, 0xe0, 0xf5, 0xc3, 0x37, 0x9f, 0x5f, 0x4f, 0xb9, 0xba, 0xcc, 0x2f,
	0x0e, 0xc2, 0x34, 0xee, 0xc7, 0x3c, 0x61, 0x22, 0x88, 0x04, 0x93, 0x7d, 0xfc, 0x73, 0x29, 0xfb,
	0x52, 0x84, 0xfd, 0x69, 0xda, 0xb7, 0xed, 0x70, 0x51, 0x43, 0xf8, 0xdd, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x92, 0xf9, 0xa7, 0x8f, 0x0a, 0x00, 0x00,
}
