// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goshare/message.proto

package goshare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageType int32

const (
	// 订阅行情
	MessageType_REQ_SUBSCRIBE_MARKET_DATA MessageType = 0
	// 订阅结果
	MessageType_RSP_SUBSCRIBE_MARKET_DATA MessageType = 1
	// 有新行情
	MessageType_RTN_MARKET_DATA_UPDATE MessageType = 2
	// 订阅行情
	MessageType_REQ_UNSUBSCRIBE_MARKET_DATA MessageType = 3
	// 订阅结果
	MessageType_RSP_UNSUBSCRIBE_MARKET_DATA MessageType = 4
	// 心跳
	MessageType_HEATBEAT MessageType = 5
	// 上传tick
	MessageType_UPLOAD_TICK MessageType = 6
)

var MessageType_name = map[int32]string{
	0: "REQ_SUBSCRIBE_MARKET_DATA",
	1: "RSP_SUBSCRIBE_MARKET_DATA",
	2: "RTN_MARKET_DATA_UPDATE",
	3: "REQ_UNSUBSCRIBE_MARKET_DATA",
	4: "RSP_UNSUBSCRIBE_MARKET_DATA",
	5: "HEATBEAT",
	6: "UPLOAD_TICK",
}

var MessageType_value = map[string]int32{
	"REQ_SUBSCRIBE_MARKET_DATA":   0,
	"RSP_SUBSCRIBE_MARKET_DATA":   1,
	"RTN_MARKET_DATA_UPDATE":      2,
	"REQ_UNSUBSCRIBE_MARKET_DATA": 3,
	"RSP_UNSUBSCRIBE_MARKET_DATA": 4,
	"HEATBEAT":                    5,
	"UPLOAD_TICK":                 6,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9068ab39e65d2af6, []int{0}
}

// Message 消息
type Message struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=goshare.MessageType" json:"type"`
	Target               string      `protobuf:"bytes,2,opt,name=target,proto3" json:"target"`
	Data                 []byte      `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_9068ab39e65d2af6, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_REQ_SUBSCRIBE_MARKET_DATA
}

func (m *Message) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// MessageList 消息list
type MessageList struct {
	List                 []*Message `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MessageList) Reset()         { *m = MessageList{} }
func (m *MessageList) String() string { return proto.CompactTextString(m) }
func (*MessageList) ProtoMessage()    {}
func (*MessageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9068ab39e65d2af6, []int{1}
}

func (m *MessageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageList.Unmarshal(m, b)
}
func (m *MessageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageList.Marshal(b, m, deterministic)
}
func (m *MessageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageList.Merge(m, src)
}
func (m *MessageList) XXX_Size() int {
	return xxx_messageInfo_MessageList.Size(m)
}
func (m *MessageList) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageList.DiscardUnknown(m)
}

var xxx_messageInfo_MessageList proto.InternalMessageInfo

func (m *MessageList) GetList() []*Message {
	if m != nil {
		return m.List
	}
	return nil
}

type StreamMessage struct {
	Type                 MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=goshare.MessageType" json:"type"`
	Target               string      `protobuf:"bytes,2,opt,name=target,proto3" json:"target"`
	Data                 string      `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamMessage) Reset()         { *m = StreamMessage{} }
func (m *StreamMessage) String() string { return proto.CompactTextString(m) }
func (*StreamMessage) ProtoMessage()    {}
func (*StreamMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9068ab39e65d2af6, []int{2}
}

func (m *StreamMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMessage.Unmarshal(m, b)
}
func (m *StreamMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMessage.Marshal(b, m, deterministic)
}
func (m *StreamMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMessage.Merge(m, src)
}
func (m *StreamMessage) XXX_Size() int {
	return xxx_messageInfo_StreamMessage.Size(m)
}
func (m *StreamMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMessage.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMessage proto.InternalMessageInfo

func (m *StreamMessage) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_REQ_SUBSCRIBE_MARKET_DATA
}

func (m *StreamMessage) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *StreamMessage) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("goshare.MessageType", MessageType_name, MessageType_value)
	proto.RegisterType((*Message)(nil), "goshare.Message")
	proto.RegisterType((*MessageList)(nil), "goshare.MessageList")
	proto.RegisterType((*StreamMessage)(nil), "goshare.StreamMessage")
}

func init() { proto.RegisterFile("goshare/message.proto", fileDescriptor_9068ab39e65d2af6) }

var fileDescriptor_9068ab39e65d2af6 = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0x5f, 0x4b, 0xf3, 0x30,
	0x18, 0xc5, 0xdf, 0x6e, 0x7d, 0x37, 0xf7, 0x6c, 0x6a, 0x09, 0x3a, 0xaa, 0x22, 0x96, 0xe1, 0x45,
	0x51, 0x6c, 0x61, 0xfb, 0x04, 0xe9, 0x56, 0x70, 0xec, 0x8f, 0x35, 0x4d, 0x6f, 0xbc, 0x29, 0xd9,
	0x0c, 0x5d, 0x61, 0xb5, 0x23, 0x89, 0x17, 0xfb, 0x86, 0x7e, 0x2c, 0x59, 0x56, 0x44, 0xc4, 0x5d,
	0x7a, 0x97, 0x9c, 0xdf, 0xc9, 0xc9, 0xe1, 0x79, 0xe0, 0x3c, 0x2b, 0xe5, 0x8a, 0x09, 0xee, 0x17,
	0x5c, 0x4a, 0x96, 0x71, 0x6f, 0x23, 0x4a, 0x55, 0xa2, 0x66, 0x25, 0xf7, 0x52, 0x68, 0xce, 0xf6,
	0x04, 0xb9, 0x60, 0xaa, 0xed, 0x86, 0xdb, 0x86, 0x63, 0xb8, 0x27, 0xfd, 0x33, 0xaf, 0xb2, 0x78,
	0x15, 0xa7, 0xdb, 0x0d, 0x27, 0xda, 0x81, 0xba, 0xd0, 0x50, 0x4c, 0x64, 0x5c, 0xd9, 0x35, 0xc7,
	0x70, 0x5b, 0xa4, 0xba, 0x21, 0x04, 0xe6, 0x2b, 0x53, 0xcc, 0xae, 0x3b, 0x86, 0xdb, 0x21, 0xfa,
	0xdc, 0x1b, 0x40, 0xbb, 0x0a, 0x98, 0xe6, 0x52, 0xa1, 0x5b, 0x30, 0xd7, 0xb9, 0x54, 0xb6, 0xe1,
	0xd4, 0xdd, 0x76, 0xdf, 0xfa, 0xf9, 0x09, 0xd1, 0xb4, 0xc7, 0xe1, 0x38, 0x56, 0x82, 0xb3, 0xe2,
	0x6f, 0xba, 0xb5, 0xf6, 0xdd, 0xee, 0x3e, 0x8c, 0xaf, 0x72, 0xbb, 0x04, 0x74, 0x0d, 0x17, 0x24,
	0x7c, 0x4e, 0xe3, 0x24, 0x88, 0x87, 0x64, 0x1c, 0x84, 0xe9, 0x0c, 0x93, 0x49, 0x48, 0xd3, 0x11,
	0xa6, 0xd8, 0xfa, 0xa7, 0x71, 0x1c, 0x1d, 0xc0, 0x06, 0xba, 0x84, 0x2e, 0xa1, 0xf3, 0xef, 0x62,
	0x9a, 0x44, 0x23, 0x4c, 0x43, 0xab, 0x86, 0x6e, 0xe0, 0x6a, 0x97, 0x9c, 0xcc, 0x7f, 0x7f, 0x5c,
	0xd7, 0x86, 0x38, 0x3a, 0x68, 0x30, 0x51, 0x07, 0x8e, 0x1e, 0x43, 0x4c, 0x83, 0x10, 0x53, 0xeb,
	0x3f, 0x3a, 0x85, 0x76, 0x12, 0x4d, 0x9f, 0xf0, 0x28, 0xa5, 0xe3, 0xe1, 0xc4, 0x6a, 0x04, 0x0f,
	0x2f, 0xf7, 0x59, 0xae, 0x56, 0xef, 0x0b, 0x6f, 0x59, 0x16, 0x7e, 0x91, 0xbf, 0x71, 0xc1, 0xd6,
	0x82, 0x4b, 0x5f, 0xef, 0x5b, 0xfa, 0x52, 0x2c, 0xfd, 0xac, 0xf4, 0xab, 0xb9, 0x2d, 0x1a, 0x5a,
	0x1e, 0x7c, 0x06, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x61, 0x60, 0xe9, 0x1f, 0x02, 0x00, 0x00,
}
