// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goshare/order.proto

package goshare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 投机套保标志
type HedgeType int32

const (
	// 投机
	HedgeType_SPECULATION HedgeType = 0
	// 套利
	HedgeType_ARBITRAGE HedgeType = 1
	// 套保
	HedgeType_HEDGE HedgeType = 2
	// 投机2(特别标志)
	HedgeType_SPECULATION2 HedgeType = 3
)

var HedgeType_name = map[int32]string{
	0: "SPECULATION",
	1: "ARBITRAGE",
	2: "HEDGE",
	3: "SPECULATION2",
}

var HedgeType_value = map[string]int32{
	"SPECULATION":  0,
	"ARBITRAGE":    1,
	"HEDGE":        2,
	"SPECULATION2": 3,
}

func (x HedgeType) String() string {
	return proto.EnumName(HedgeType_name, int32(x))
}

func (HedgeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{0}
}

type OrderStatus int32

const (
	// 完全成交
	OrderStatus_DONE OrderStatus = 0
	// 部分成交还在队列中
	OrderStatus_PENDING_WITH_PARTIAL_DONE OrderStatus = 1
	// 部分成交且已撤单
	OrderStatus_CANCELED_WITH_PARTIAL_DONE OrderStatus = 2
	// 队列中
	OrderStatus_PENDING OrderStatus = 3
	// 已经撤单
	OrderStatus_CANCELED OrderStatus = 4
	// 未知
	OrderStatus_UNKOWN OrderStatus = 5
)

var OrderStatus_name = map[int32]string{
	0: "DONE",
	1: "PENDING_WITH_PARTIAL_DONE",
	2: "CANCELED_WITH_PARTIAL_DONE",
	3: "PENDING",
	4: "CANCELED",
	5: "UNKOWN",
}

var OrderStatus_value = map[string]int32{
	"DONE":                       0,
	"PENDING_WITH_PARTIAL_DONE":  1,
	"CANCELED_WITH_PARTIAL_DONE": 2,
	"PENDING":                    3,
	"CANCELED":                   4,
	"UNKOWN":                     5,
}

func (x OrderStatus) String() string {
	return proto.EnumName(OrderStatus_name, int32(x))
}

func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{1}
}

type OrderPriceType int32

const (
	// 限价
	OrderPriceType_LIMIT_PRICE OrderPriceType = 0
	// 市价
	OrderPriceType_MARKET_PRICE OrderPriceType = 1
	// 最优价
	OrderPriceType_BEST_PRICE OrderPriceType = 2
	// 最新价
	OrderPriceType_LAST_PRICE OrderPriceType = 3
)

var OrderPriceType_name = map[int32]string{
	0: "LIMIT_PRICE",
	1: "MARKET_PRICE",
	2: "BEST_PRICE",
	3: "LAST_PRICE",
}

var OrderPriceType_value = map[string]int32{
	"LIMIT_PRICE":  0,
	"MARKET_PRICE": 1,
	"BEST_PRICE":   2,
	"LAST_PRICE":   3,
}

func (x OrderPriceType) String() string {
	return proto.EnumName(OrderPriceType_name, int32(x))
}

func (OrderPriceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{2}
}

type OffsetFlag int32

const (
	// 开仓
	OffsetFlag_OPEN OffsetFlag = 0
	// 平仓
	OffsetFlag_CLOSE OffsetFlag = 1
	// 强平
	OffsetFlag_FORCE_CLOSE OffsetFlag = 2
	// 平今
	OffsetFlag_CLOSE_TODAY OffsetFlag = 3
	// 平昨
	OffsetFlag_CLOSE_YESTERDAY OffsetFlag = 4
)

var OffsetFlag_name = map[int32]string{
	0: "OPEN",
	1: "CLOSE",
	2: "FORCE_CLOSE",
	3: "CLOSE_TODAY",
	4: "CLOSE_YESTERDAY",
}

var OffsetFlag_value = map[string]int32{
	"OPEN":            0,
	"CLOSE":           1,
	"FORCE_CLOSE":     2,
	"CLOSE_TODAY":     3,
	"CLOSE_YESTERDAY": 4,
}

func (x OffsetFlag) String() string {
	return proto.EnumName(OffsetFlag_name, int32(x))
}

func (OffsetFlag) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{3}
}

// 报单方向
type DirectionType int32

const (
	DirectionType_LONG  DirectionType = 0
	DirectionType_SHORT DirectionType = 1
	DirectionType_NET   DirectionType = 2
)

var DirectionType_name = map[int32]string{
	0: "LONG",
	1: "SHORT",
	2: "NET",
}

var DirectionType_value = map[string]int32{
	"LONG":  0,
	"SHORT": 1,
	"NET":   2,
}

func (x DirectionType) String() string {
	return proto.EnumName(DirectionType_name, int32(x))
}

func (DirectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{4}
}

// 组合方向
type CombDirectionType int32

const (
	CombDirectionType_COMB   CombDirectionType = 0
	CombDirectionType_UNCOMB CombDirectionType = 1
)

var CombDirectionType_name = map[int32]string{
	0: "COMB",
	1: "UNCOMB",
}

var CombDirectionType_value = map[string]int32{
	"COMB":   0,
	"UNCOMB": 1,
}

func (x CombDirectionType) String() string {
	return proto.EnumName(CombDirectionType_name, int32(x))
}

func (CombDirectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{5}
}

// 强平类型
type ForceCloseReason int32

const (
	// 资金不足
	ForceCloseReason_NOT_ENOUGH_MARGIN ForceCloseReason = 0
	// 客户超仓
	ForceCloseReason_client_over_position_limit ForceCloseReason = 1
	// 会员超仓
	ForceCloseReason_broker_over_poisition_limit ForceCloseReason = 2
	// 违规
	ForceCloseReason_violation ForceCloseReason = 3
	// 其它
	ForceCloseReason_other ForceCloseReason = 4
	// 自然人临近交割
	ForceCloseReason_person_deliver ForceCloseReason = 5
)

var ForceCloseReason_name = map[int32]string{
	0: "NOT_ENOUGH_MARGIN",
	1: "client_over_position_limit",
	2: "broker_over_poisition_limit",
	3: "violation",
	4: "other",
	5: "person_deliver",
}

var ForceCloseReason_value = map[string]int32{
	"NOT_ENOUGH_MARGIN":           0,
	"client_over_position_limit":  1,
	"broker_over_poisition_limit": 2,
	"violation":                   3,
	"other":                       4,
	"person_deliver":              5,
}

func (x ForceCloseReason) String() string {
	return proto.EnumName(ForceCloseReason_name, int32(x))
}

func (ForceCloseReason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{6}
}

// 报单来源
type OrderSourceType int32

const (
	// 客户
	OrderSourceType_CLIENT OrderSourceType = 0
	// 管理员
	OrderSourceType_ADMINISTRATOR OrderSourceType = 1
	// 风控
	OrderSourceType_RISK_SRV OrderSourceType = 2
	// 手机端
	OrderSourceType_MOBILE OrderSourceType = 3
	// PC端
	OrderSourceType_PC OrderSourceType = 4
	// 结算衍生
	OrderSourceType_SETTLEMENT_DERIVED OrderSourceType = 5
	// 套利单衍生
	OrderSourceType_COMBINATION_DERIVED OrderSourceType = 6
	// 多路径平仓衍生
	OrderSourceType_MULTI_ROUTE_CLOSE_DERIVED OrderSourceType = 7
	// 分红送股
	OrderSourceType_PLACEMENT_SHARE OrderSourceType = 8
	// 回购操作
	OrderSourceType_REPURCHASE OrderSourceType = 9
	// CTP上传
	OrderSourceType_CTP_UPLOAD OrderSourceType = 10
)

var OrderSourceType_name = map[int32]string{
	0:  "CLIENT",
	1:  "ADMINISTRATOR",
	2:  "RISK_SRV",
	3:  "MOBILE",
	4:  "PC",
	5:  "SETTLEMENT_DERIVED",
	6:  "COMBINATION_DERIVED",
	7:  "MULTI_ROUTE_CLOSE_DERIVED",
	8:  "PLACEMENT_SHARE",
	9:  "REPURCHASE",
	10: "CTP_UPLOAD",
}

var OrderSourceType_value = map[string]int32{
	"CLIENT":                    0,
	"ADMINISTRATOR":             1,
	"RISK_SRV":                  2,
	"MOBILE":                    3,
	"PC":                        4,
	"SETTLEMENT_DERIVED":        5,
	"COMBINATION_DERIVED":       6,
	"MULTI_ROUTE_CLOSE_DERIVED": 7,
	"PLACEMENT_SHARE":           8,
	"REPURCHASE":                9,
	"CTP_UPLOAD":                10,
}

func (x OrderSourceType) String() string {
	return proto.EnumName(OrderSourceType_name, int32(x))
}

func (OrderSourceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{7}
}

// 委托
type Order struct {
	UserId               string        `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"userId"`
	TaId                 string        `protobuf:"bytes,2,opt,name=ta_id,json=taId,proto3" json:"taId"`
	BuId                 string        `protobuf:"bytes,3,opt,name=bu_id,json=buId,proto3" json:"buId"`
	Exchange             string        `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string        `protobuf:"bytes,5,opt,name=symbol,proto3" json:"symbol"`
	Product              string        `protobuf:"bytes,6,opt,name=product,proto3" json:"product"`
	OrderRef             string        `protobuf:"bytes,7,opt,name=order_ref,json=orderRef,proto3" json:"orderRef"`
	Direction            DirectionType `protobuf:"varint,8,opt,name=direction,proto3,enum=goshare.DirectionType" json:"direction"`
	Offset               int32         `protobuf:"varint,9,opt,name=offset,proto3" json:"offset"`
	Price                float64       `protobuf:"fixed64,10,opt,name=price,proto3" json:"price"`
	Volume               int32         `protobuf:"varint,11,opt,name=volume,proto3" json:"volume"`
	VolumeTraded         int32         `protobuf:"varint,12,opt,name=volume_traded,json=volumeTraded,proto3" json:"volumeTraded"`
	VolumeCanceled       int32         `protobuf:"varint,13,opt,name=volume_canceled,json=volumeCanceled,proto3" json:"volumeCanceled"`
	Status               int32         `protobuf:"varint,14,opt,name=status,proto3" json:"status"`
	PriceType            int32         `protobuf:"varint,15,opt,name=price_type,json=priceType,proto3" json:"priceType"`
	FrozenCommission     float64       `protobuf:"fixed64,16,opt,name=frozen_commission,json=frozenCommission,proto3" json:"frozenCommission"`
	SendOrderTime        int64         `protobuf:"varint,17,opt,name=send_order_time,json=sendOrderTime,proto3" json:"sendOrderTime"`
	SendOrderTradingDay  int32         `protobuf:"varint,18,opt,name=send_order_trading_day,json=sendOrderTradingDay,proto3" json:"sendOrderTradingDay"`
	StatusMsg            string        `protobuf:"bytes,19,opt,name=status_msg,json=statusMsg,proto3" json:"statusMsg"`
	ForceCloseType       int32         `protobuf:"varint,20,opt,name=force_close_type,json=forceCloseType,proto3" json:"forceCloseType"`
	OrderSourceType      int32         `protobuf:"varint,21,opt,name=order_source_type,json=orderSourceType,proto3" json:"orderSourceType"`
	HedgeType            int32         `protobuf:"varint,22,opt,name=hedge_type,json=hedgeType,proto3" json:"hedgeType"`
	UserProductInfo      string        `protobuf:"bytes,23,opt,name=user_product_info,json=userProductInfo,proto3" json:"userProductInfo"`
	ExchangeOrderId      string        `protobuf:"bytes,24,opt,name=exchange_order_id,json=exchangeOrderId,proto3" json:"exchangeOrderId"`
	TimeConditionType    int32         `protobuf:"varint,25,opt,name=time_condition_type,json=timeConditionType,proto3" json:"timeConditionType"`
	IsPending            bool          `protobuf:"varint,26,opt,name=is_pending,json=isPending,proto3" json:"isPending"`
	Commission           float64       `protobuf:"fixed64,27,opt,name=commission,proto3" json:"commission"`
	ProductType          string        `protobuf:"bytes,28,opt,name=product_type,json=productType,proto3" json:"productType"`
	TradedAmount         float64       `protobuf:"fixed64,29,opt,name=traded_amount,json=tradedAmount,proto3" json:"tradedAmount"`
	Multiple             int32         `protobuf:"varint,30,opt,name=multiple,proto3" json:"multiple"`
	PriceTick            float64       `protobuf:"fixed64,31,opt,name=price_tick,json=priceTick,proto3" json:"priceTick"`
	LastPrice            float64       `protobuf:"fixed64,32,opt,name=last_price,json=lastPrice,proto3" json:"lastPrice"`
	FrozenMargin         float64       `protobuf:"fixed64,33,opt,name=frozen_margin,json=frozenMargin,proto3" json:"frozenMargin"`
	SymbolName           string        `protobuf:"bytes,34,opt,name=symbol_name,json=symbolName,proto3" json:"symbolName"`
	Reason               string        `protobuf:"bytes,35,opt,name=reason,proto3" json:"reason"`
	StampTax             float64       `protobuf:"fixed64,36,opt,name=stamp_tax,json=stampTax,proto3" json:"stampTax"`
	TransferFee          float64       `protobuf:"fixed64,37,opt,name=transfer_fee,json=transferFee,proto3" json:"transferFee"`
	UserName             string        `protobuf:"bytes,38,opt,name=user_name,json=userName,proto3" json:"userName"`
	Ip                   string        `protobuf:"bytes,39,opt,name=ip,proto3" json:"ip"`
	Mac                  string        `protobuf:"bytes,40,opt,name=mac,proto3" json:"mac"`
	Branch               string        `protobuf:"bytes,41,opt,name=branch,proto3" json:"branch"`
	BranchName           string        `protobuf:"bytes,42,opt,name=branch_name,json=branchName,proto3" json:"branchName"`
	BuType               int32         `protobuf:"varint,43,opt,name=bu_type,json=buType,proto3" json:"buType"`
	Debug                string        `protobuf:"bytes,44,opt,name=debug,proto3" json:"debug"`
	SessionId            int32         `protobuf:"varint,45,opt,name=session_id,json=sessionId,proto3" json:"sessionId"`
	ClientTag            int64         `protobuf:"varint,46,opt,name=client_tag,json=clientTag,proto3" json:"clientTag"`
	FrontId              int32         `protobuf:"varint,47,opt,name=front_id,json=frontId,proto3" json:"frontId"`
	RequestId            int32         `protobuf:"varint,48,opt,name=request_id,json=requestId,proto3" json:"requestId"`
	LocalOrderSeq        int32         `protobuf:"varint,49,opt,name=local_order_seq,json=localOrderSeq,proto3" json:"localOrderSeq"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Order) GetTaId() string {
	if m != nil {
		return m.TaId
	}
	return ""
}

func (m *Order) GetBuId() string {
	if m != nil {
		return m.BuId
	}
	return ""
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Order) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Order) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *Order) GetOrderRef() string {
	if m != nil {
		return m.OrderRef
	}
	return ""
}

func (m *Order) GetDirection() DirectionType {
	if m != nil {
		return m.Direction
	}
	return DirectionType_LONG
}

func (m *Order) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Order) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Order) GetVolumeTraded() int32 {
	if m != nil {
		return m.VolumeTraded
	}
	return 0
}

func (m *Order) GetVolumeCanceled() int32 {
	if m != nil {
		return m.VolumeCanceled
	}
	return 0
}

func (m *Order) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Order) GetPriceType() int32 {
	if m != nil {
		return m.PriceType
	}
	return 0
}

func (m *Order) GetFrozenCommission() float64 {
	if m != nil {
		return m.FrozenCommission
	}
	return 0
}

func (m *Order) GetSendOrderTime() int64 {
	if m != nil {
		return m.SendOrderTime
	}
	return 0
}

func (m *Order) GetSendOrderTradingDay() int32 {
	if m != nil {
		return m.SendOrderTradingDay
	}
	return 0
}

func (m *Order) GetStatusMsg() string {
	if m != nil {
		return m.StatusMsg
	}
	return ""
}

func (m *Order) GetForceCloseType() int32 {
	if m != nil {
		return m.ForceCloseType
	}
	return 0
}

func (m *Order) GetOrderSourceType() int32 {
	if m != nil {
		return m.OrderSourceType
	}
	return 0
}

func (m *Order) GetHedgeType() int32 {
	if m != nil {
		return m.HedgeType
	}
	return 0
}

func (m *Order) GetUserProductInfo() string {
	if m != nil {
		return m.UserProductInfo
	}
	return ""
}

func (m *Order) GetExchangeOrderId() string {
	if m != nil {
		return m.ExchangeOrderId
	}
	return ""
}

func (m *Order) GetTimeConditionType() int32 {
	if m != nil {
		return m.TimeConditionType
	}
	return 0
}

func (m *Order) GetIsPending() bool {
	if m != nil {
		return m.IsPending
	}
	return false
}

func (m *Order) GetCommission() float64 {
	if m != nil {
		return m.Commission
	}
	return 0
}

func (m *Order) GetProductType() string {
	if m != nil {
		return m.ProductType
	}
	return ""
}

func (m *Order) GetTradedAmount() float64 {
	if m != nil {
		return m.TradedAmount
	}
	return 0
}

func (m *Order) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *Order) GetPriceTick() float64 {
	if m != nil {
		return m.PriceTick
	}
	return 0
}

func (m *Order) GetLastPrice() float64 {
	if m != nil {
		return m.LastPrice
	}
	return 0
}

func (m *Order) GetFrozenMargin() float64 {
	if m != nil {
		return m.FrozenMargin
	}
	return 0
}

func (m *Order) GetSymbolName() string {
	if m != nil {
		return m.SymbolName
	}
	return ""
}

func (m *Order) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Order) GetStampTax() float64 {
	if m != nil {
		return m.StampTax
	}
	return 0
}

func (m *Order) GetTransferFee() float64 {
	if m != nil {
		return m.TransferFee
	}
	return 0
}

func (m *Order) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *Order) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Order) GetMac() string {
	if m != nil {
		return m.Mac
	}
	return ""
}

func (m *Order) GetBranch() string {
	if m != nil {
		return m.Branch
	}
	return ""
}

func (m *Order) GetBranchName() string {
	if m != nil {
		return m.BranchName
	}
	return ""
}

func (m *Order) GetBuType() int32 {
	if m != nil {
		return m.BuType
	}
	return 0
}

func (m *Order) GetDebug() string {
	if m != nil {
		return m.Debug
	}
	return ""
}

func (m *Order) GetSessionId() int32 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *Order) GetClientTag() int64 {
	if m != nil {
		return m.ClientTag
	}
	return 0
}

func (m *Order) GetFrontId() int32 {
	if m != nil {
		return m.FrontId
	}
	return 0
}

func (m *Order) GetRequestId() int32 {
	if m != nil {
		return m.RequestId
	}
	return 0
}

func (m *Order) GetLocalOrderSeq() int32 {
	if m != nil {
		return m.LocalOrderSeq
	}
	return 0
}

type OrderList struct {
	List                 []*Order `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderList) Reset()         { *m = OrderList{} }
func (m *OrderList) String() string { return proto.CompactTextString(m) }
func (*OrderList) ProtoMessage()    {}
func (*OrderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{1}
}

func (m *OrderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderList.Unmarshal(m, b)
}
func (m *OrderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderList.Marshal(b, m, deterministic)
}
func (m *OrderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderList.Merge(m, src)
}
func (m *OrderList) XXX_Size() int {
	return xxx_messageInfo_OrderList.Size(m)
}
func (m *OrderList) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderList.DiscardUnknown(m)
}

var xxx_messageInfo_OrderList proto.InternalMessageInfo

func (m *OrderList) GetList() []*Order {
	if m != nil {
		return m.List
	}
	return nil
}

type JointOrder struct {
	LocalOrder           *Order   `protobuf:"bytes,1,opt,name=local_order,json=localOrder,proto3" json:"localOrder"`
	ExchangeOrder        *Order   `protobuf:"bytes,2,opt,name=exchange_order,json=exchangeOrder,proto3" json:"exchangeOrder"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JointOrder) Reset()         { *m = JointOrder{} }
func (m *JointOrder) String() string { return proto.CompactTextString(m) }
func (*JointOrder) ProtoMessage()    {}
func (*JointOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3576037e32e300b, []int{2}
}

func (m *JointOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JointOrder.Unmarshal(m, b)
}
func (m *JointOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JointOrder.Marshal(b, m, deterministic)
}
func (m *JointOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JointOrder.Merge(m, src)
}
func (m *JointOrder) XXX_Size() int {
	return xxx_messageInfo_JointOrder.Size(m)
}
func (m *JointOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_JointOrder.DiscardUnknown(m)
}

var xxx_messageInfo_JointOrder proto.InternalMessageInfo

func (m *JointOrder) GetLocalOrder() *Order {
	if m != nil {
		return m.LocalOrder
	}
	return nil
}

func (m *JointOrder) GetExchangeOrder() *Order {
	if m != nil {
		return m.ExchangeOrder
	}
	return nil
}

func init() {
	proto.RegisterEnum("goshare.HedgeType", HedgeType_name, HedgeType_value)
	proto.RegisterEnum("goshare.OrderStatus", OrderStatus_name, OrderStatus_value)
	proto.RegisterEnum("goshare.OrderPriceType", OrderPriceType_name, OrderPriceType_value)
	proto.RegisterEnum("goshare.OffsetFlag", OffsetFlag_name, OffsetFlag_value)
	proto.RegisterEnum("goshare.DirectionType", DirectionType_name, DirectionType_value)
	proto.RegisterEnum("goshare.CombDirectionType", CombDirectionType_name, CombDirectionType_value)
	proto.RegisterEnum("goshare.ForceCloseReason", ForceCloseReason_name, ForceCloseReason_value)
	proto.RegisterEnum("goshare.OrderSourceType", OrderSourceType_name, OrderSourceType_value)
	proto.RegisterType((*Order)(nil), "goshare.Order")
	proto.RegisterType((*OrderList)(nil), "goshare.OrderList")
	proto.RegisterType((*JointOrder)(nil), "goshare.JointOrder")
}

func init() { proto.RegisterFile("goshare/order.proto", fileDescriptor_e3576037e32e300b) }

var fileDescriptor_e3576037e32e300b = []byte{
	// 1463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x96, 0xeb, 0x76, 0xdb, 0xb8,
	0x11, 0x80, 0x43, 0xdd, 0x35, 0xba, 0xc1, 0x70, 0xd6, 0x41, 0x92, 0x26, 0xd1, 0x3a, 0xed, 0xae,
	0x56, 0x69, 0xac, 0x36, 0xdb, 0x3e, 0x00, 0x4d, 0x31, 0x16, 0x1b, 0x89, 0xd4, 0xa1, 0xe8, 0xdd,
	0xa6, 0x7f, 0x78, 0x28, 0x12, 0x92, 0x79, 0xc2, 0x8b, 0x42, 0x52, 0x3e, 0x71, 0xcf, 0xe9, 0x7b,
	0xf4, 0x77, 0x5f, 0xaa, 0xaf, 0xd3, 0x83, 0x01, 0xa5, 0xd8, 0xcd, 0xfe, 0xe3, 0x7c, 0x33, 0x98,
	0x0b, 0x30, 0x03, 0x10, 0x4e, 0xb7, 0x69, 0x7e, 0xe3, 0x65, 0x7c, 0x92, 0x66, 0x01, 0xcf, 0x2e,
	0x76, 0x59, 0x5a, 0xa4, 0xb4, 0x59, 0xc2, 0xf3, 0xff, 0x74, 0xa1, 0x6e, 0x09, 0x05, 0x7d, 0x02,
	0xcd, 0x7d, 0xce, 0x33, 0x37, 0x0c, 0x98, 0x32, 0x54, 0x46, 0x6d, 0xbb, 0x21, 0x44, 0x23, 0xa0,
	0xa7, 0x50, 0x2f, 0x3c, 0x81, 0x2b, 0x88, 0x6b, 0x85, 0x27, 0xe1, 0x7a, 0x2f, 0x60, 0x55, 0xc2,
	0xf5, 0xde, 0x08, 0xe8, 0x33, 0x68, 0xf1, 0x2f, 0xfe, 0x8d, 0x97, 0x6c, 0x39, 0xab, 0x21, 0x3f,
	0xca, 0xf4, 0x0c, 0x1a, 0xf9, 0x5d, 0xbc, 0x4e, 0x23, 0x56, 0x97, 0xde, 0xa5, 0x44, 0x19, 0x34,
	0x77, 0x59, 0x1a, 0xec, 0xfd, 0x82, 0x35, 0x50, 0x71, 0x10, 0xe9, 0x73, 0x68, 0x63, 0xca, 0x6e,
	0xc6, 0x37, 0xac, 0x29, 0xdd, 0x21, 0xb0, 0xf9, 0x86, 0xfe, 0x05, 0xda, 0x41, 0x98, 0x71, 0xbf,
	0x08, 0xd3, 0x84, 0xb5, 0x86, 0xca, 0xa8, 0xff, 0xee, 0xec, 0xa2, 0x2c, 0xea, 0x62, 0x7a, 0xd0,
	0x38, 0x77, 0x3b, 0x6e, 0x7f, 0x35, 0x14, 0x49, 0xa4, 0x9b, 0x4d, 0xce, 0x0b, 0xd6, 0x1e, 0x2a,
	0xa3, 0xba, 0x5d, 0x4a, 0xf4, 0x31, 0xd4, 0x77, 0x59, 0xe8, 0x73, 0x06, 0x43, 0x65, 0xa4, 0xd8,
	0x52, 0x10, 0xd6, 0xb7, 0x69, 0xb4, 0x8f, 0x39, 0xeb, 0x48, 0x6b, 0x29, 0xd1, 0xd7, 0xd0, 0x93,
	0x5f, 0x6e, 0x91, 0x79, 0x01, 0x0f, 0x58, 0x17, 0xd5, 0x5d, 0x09, 0x1d, 0x64, 0xf4, 0x47, 0x18,
	0x94, 0x46, 0xbe, 0x97, 0xf8, 0x3c, 0xe2, 0x01, 0xeb, 0xa1, 0x59, 0x5f, 0x62, 0xad, 0xa4, 0xb8,
	0x31, 0x85, 0x57, 0xec, 0x73, 0xd6, 0x97, 0x51, 0xa4, 0x44, 0x5f, 0x00, 0x60, 0x1a, 0x6e, 0x71,
	0xb7, 0xe3, 0x6c, 0x80, 0xba, 0x36, 0x12, 0x51, 0x15, 0x7d, 0x03, 0x27, 0x9b, 0x2c, 0xfd, 0x27,
	0x4f, 0x5c, 0x3f, 0x8d, 0xe3, 0x30, 0xcf, 0xc5, 0x46, 0x10, 0x4c, 0x9f, 0x48, 0x85, 0x76, 0xe4,
	0xf4, 0x07, 0x18, 0xe4, 0x3c, 0x09, 0x5c, 0xb9, 0x9f, 0x45, 0x18, 0x73, 0x76, 0x32, 0x54, 0x46,
	0x55, 0xbb, 0x27, 0x30, 0x9e, 0xbf, 0x13, 0xc6, 0x9c, 0xfe, 0x0c, 0x67, 0xf7, 0xed, 0x32, 0x2f,
	0x08, 0x93, 0xad, 0x1b, 0x78, 0x77, 0x8c, 0x62, 0xfc, 0xd3, 0xaf, 0xe6, 0x52, 0x37, 0xf5, 0xee,
	0x44, 0xa2, 0x32, 0x65, 0x37, 0xce, 0xb7, 0xec, 0x14, 0x0f, 0xaa, 0x2d, 0xc9, 0x22, 0xdf, 0xd2,
	0x11, 0x90, 0x4d, 0x9a, 0xf9, 0xdc, 0xf5, 0xa3, 0x34, 0x2f, 0xab, 0x79, 0x2c, 0x77, 0x02, 0xb9,
	0x26, 0x30, 0x96, 0x34, 0x86, 0x13, 0x19, 0x38, 0x4f, 0xf7, 0xd9, 0xa1, 0xf0, 0xef, 0xd0, 0x74,
	0x80, 0x8a, 0x15, 0x72, 0xb4, 0x7d, 0x01, 0x70, 0xc3, 0x83, 0x6d, 0x69, 0x74, 0x26, 0x77, 0x07,
	0xc9, 0xc1, 0x15, 0x36, 0x73, 0xd9, 0x4b, 0x6e, 0x98, 0x6c, 0x52, 0xf6, 0x04, 0x53, 0x1b, 0x08,
	0xc5, 0x52, 0x72, 0x23, 0xd9, 0xa4, 0xc2, 0xf6, 0xd0, 0xa5, 0x65, 0xe1, 0x61, 0xc0, 0x98, 0xb4,
	0x3d, 0x28, 0xb0, 0x66, 0x23, 0xa0, 0x17, 0x70, 0x2a, 0x76, 0xcf, 0xf5, 0xd3, 0x24, 0x08, 0x45,
	0x4b, 0xc9, 0xf8, 0x4f, 0x31, 0xfe, 0x89, 0x50, 0x69, 0x07, 0xcd, 0x21, 0xcd, 0x30, 0x77, 0x77,
	0x3c, 0x11, 0x9b, 0xc5, 0x9e, 0x0d, 0x95, 0x51, 0xcb, 0x6e, 0x87, 0xf9, 0x52, 0x02, 0xfa, 0x12,
	0xe0, 0xde, 0xe9, 0x3d, 0xc7, 0xd3, 0xbb, 0x47, 0xe8, 0xf7, 0xd0, 0x3d, 0x54, 0x80, 0x71, 0x7e,
	0x87, 0x59, 0x75, 0x4a, 0x86, 0x11, 0x5e, 0x43, 0x4f, 0x76, 0xa1, 0xeb, 0xc5, 0xe9, 0x3e, 0x29,
	0xd8, 0x0b, 0xf4, 0xd2, 0x95, 0x50, 0x45, 0x26, 0x06, 0x33, 0xde, 0x47, 0x45, 0xb8, 0x8b, 0x38,
	0x7b, 0x89, 0xb9, 0x1e, 0xe5, 0x7b, 0x7d, 0x16, 0xfa, 0x9f, 0xd8, 0x2b, 0x5c, 0x5d, 0xf6, 0x59,
	0xe8, 0x7f, 0x12, 0xea, 0xc8, 0xcb, 0x0b, 0x57, 0xce, 0xc7, 0x50, 0xaa, 0x05, 0x59, 0xe2, 0x8c,
	0xbc, 0x86, 0x5e, 0xd9, 0x86, 0xb1, 0x97, 0x6d, 0xc3, 0x84, 0x7d, 0x2f, 0xc3, 0x4b, 0xb8, 0x40,
	0x46, 0x5f, 0x41, 0x47, 0x4e, 0xbb, 0x9b, 0x78, 0x31, 0x67, 0xe7, 0x58, 0x05, 0x48, 0x64, 0x7a,
	0x31, 0x4e, 0x5a, 0xc6, 0xbd, 0x3c, 0x4d, 0xd8, 0x6b, 0x79, 0x39, 0x48, 0x49, 0x5c, 0x01, 0x79,
	0xe1, 0xc5, 0x3b, 0xb7, 0xf0, 0xbe, 0xb0, 0xdf, 0xa3, 0xe7, 0x16, 0x02, 0xc7, 0xfb, 0x22, 0x36,
	0xa7, 0xc8, 0xbc, 0x24, 0xdf, 0xf0, 0xcc, 0xdd, 0x70, 0xce, 0xfe, 0x80, 0xfa, 0xce, 0x81, 0xbd,
	0xe7, 0x5c, 0xac, 0xc7, 0x36, 0xc0, 0xb0, 0x3f, 0xc8, 0x2b, 0x44, 0x00, 0x0c, 0xda, 0x87, 0x4a,
	0xb8, 0x63, 0x3f, 0x22, 0xad, 0x84, 0x3b, 0x4a, 0xa0, 0x1a, 0x7b, 0x3e, 0x1b, 0x21, 0x10, 0x9f,
	0x22, 0xad, 0x75, 0xe6, 0x25, 0xfe, 0x0d, 0xfb, 0x49, 0xa6, 0x25, 0x25, 0x51, 0x8f, 0xfc, 0x92,
	0x8e, 0xc7, 0xb2, 0x1e, 0x89, 0xd0, 0xf5, 0x13, 0x68, 0xae, 0xf7, 0xf2, 0xc8, 0xde, 0xc8, 0xa1,
	0x5e, 0xef, 0xf1, 0xb4, 0x1e, 0x43, 0x3d, 0xe0, 0xeb, 0xfd, 0x96, 0xfd, 0x11, 0xd7, 0x48, 0x01,
	0x27, 0x88, 0xe3, 0x89, 0x8b, 0xd6, 0x7b, 0x2b, 0x9b, 0xb9, 0x24, 0x46, 0x20, 0xd4, 0x7e, 0x14,
	0xf2, 0xa4, 0x70, 0x0b, 0x6f, 0xcb, 0x2e, 0x70, 0x70, 0xdb, 0x92, 0x38, 0xde, 0x96, 0x3e, 0x85,
	0xd6, 0x26, 0x4b, 0x93, 0x42, 0xac, 0x9d, 0xe0, 0xda, 0x26, 0xca, 0x72, 0x65, 0xc6, 0x3f, 0xef,
	0x79, 0x8e, 0xca, 0x3f, 0x49, 0xc7, 0x25, 0x31, 0x02, 0x71, 0x2d, 0x44, 0xa9, 0xef, 0x45, 0x65,
	0xdb, 0xe7, 0xfc, 0x33, 0xfb, 0x33, 0xda, 0xf4, 0x10, 0x63, 0xd3, 0xaf, 0xf8, 0xe7, 0xf3, 0x09,
	0xb4, 0xf1, 0x7b, 0x1e, 0xe6, 0x05, 0x3d, 0x87, 0x5a, 0x14, 0xe6, 0x05, 0x53, 0x86, 0xd5, 0x51,
	0xe7, 0x5d, 0xff, 0x78, 0xe9, 0xa2, 0x85, 0x8d, 0xba, 0xf3, 0x02, 0xe0, 0x6f, 0x69, 0x98, 0x14,
	0xf2, 0x65, 0x99, 0x40, 0xe7, 0x5e, 0x18, 0x7c, 0x5d, 0xbe, 0x5d, 0x08, 0x5f, 0x43, 0xd2, 0xbf,
	0x42, 0xff, 0xe1, 0x44, 0xe2, 0xd3, 0xf3, 0xed, 0x9a, 0xde, 0x83, 0xf1, 0x1c, 0xcf, 0xa0, 0x3d,
	0x3b, 0xde, 0x00, 0x03, 0xe8, 0xac, 0x96, 0xba, 0x76, 0x3d, 0x57, 0x1d, 0xc3, 0x32, 0xc9, 0x23,
	0xda, 0x83, 0xb6, 0x6a, 0x5f, 0x1a, 0x8e, 0xad, 0x5e, 0xe9, 0x44, 0xa1, 0x6d, 0xa8, 0xcf, 0xf4,
	0xe9, 0x95, 0x4e, 0x2a, 0x94, 0x40, 0xf7, 0x9e, 0xe9, 0x3b, 0x52, 0x1d, 0xff, 0x0b, 0x3a, 0xb2,
	0x78, 0x79, 0x15, 0xb7, 0xa0, 0x36, 0xb5, 0x4c, 0x9d, 0x3c, 0xa2, 0x2f, 0xe0, 0xe9, 0x52, 0x37,
	0xa7, 0x86, 0x79, 0xe5, 0xfe, 0x6a, 0x38, 0x33, 0x77, 0xa9, 0xda, 0x8e, 0xa1, 0xce, 0x5d, 0x54,
	0x2b, 0xf4, 0x25, 0x3c, 0xd3, 0x54, 0x53, 0xd3, 0xe7, 0xfa, 0xf4, 0x37, 0xf4, 0x15, 0xda, 0x81,
	0x66, 0xb9, 0x9c, 0x54, 0x69, 0x17, 0x5a, 0x07, 0x63, 0x52, 0xa3, 0x00, 0x8d, 0x6b, 0xf3, 0x83,
	0xf5, 0xab, 0x49, 0xea, 0xe3, 0x15, 0xf4, 0x31, 0xfc, 0xf2, 0x78, 0xdb, 0x0f, 0xa0, 0x33, 0x37,
	0x16, 0x86, 0xe3, 0x2e, 0x6d, 0x43, 0x13, 0x89, 0x10, 0xe8, 0x2e, 0x54, 0xfb, 0x83, 0x7e, 0x20,
	0x0a, 0xed, 0x03, 0x5c, 0xea, 0xab, 0x83, 0x5c, 0x11, 0xf2, 0x5c, 0x3d, 0xca, 0xd5, 0xf1, 0xdf,
	0x01, 0x2c, 0x7c, 0xed, 0xde, 0x47, 0xde, 0x56, 0x94, 0x64, 0x2d, 0x75, 0xb1, 0x2f, 0x6d, 0xa8,
	0x6b, 0x73, 0x6b, 0x25, 0x5c, 0x0c, 0xa0, 0xf3, 0xde, 0xb2, 0x35, 0xdd, 0x95, 0xa0, 0x22, 0x00,
	0x7e, 0xba, 0x8e, 0x35, 0x55, 0x3f, 0x92, 0x2a, 0x3d, 0x85, 0x81, 0x04, 0x1f, 0xf5, 0x95, 0xa3,
	0xdb, 0x02, 0xd6, 0xc6, 0x6f, 0xa1, 0xf7, 0xe0, 0xc5, 0x15, 0xce, 0xe7, 0x96, 0x79, 0x25, 0x9d,
	0xaf, 0x66, 0x96, 0xed, 0x10, 0x85, 0x36, 0xa1, 0x6a, 0xea, 0x0e, 0xa9, 0x8c, 0x7f, 0x82, 0x13,
	0x2d, 0x8d, 0xd7, 0xdf, 0x2c, 0xd1, 0xac, 0xc5, 0x25, 0x79, 0x24, 0x37, 0x02, 0xbf, 0x95, 0xf1,
	0xbf, 0x15, 0x20, 0xef, 0x8f, 0x8f, 0x84, 0x2d, 0x2f, 0x85, 0xef, 0xe0, 0xc4, 0xb4, 0x1c, 0x57,
	0x37, 0xad, 0xeb, 0xab, 0x99, 0xbb, 0x50, 0xed, 0x2b, 0x43, 0xd4, 0xf1, 0x12, 0x9e, 0x95, 0x53,
	0x92, 0xde, 0x8a, 0x9b, 0x3f, 0xcd, 0xe5, 0x05, 0x1d, 0x85, 0x71, 0x58, 0x10, 0x85, 0xbe, 0x82,
	0xe7, 0xeb, 0x2c, 0xfd, 0xc4, 0xb3, 0x83, 0x3e, 0x7c, 0x60, 0x50, 0x11, 0x0d, 0x72, 0x1b, 0xa6,
	0x91, 0x27, 0x20, 0xa9, 0x8a, 0xd4, 0xd3, 0xe2, 0x86, 0x67, 0xa4, 0x46, 0x29, 0xf4, 0x77, 0x3c,
	0xcb, 0xd3, 0xc4, 0x0d, 0x78, 0x14, 0xde, 0xf2, 0x8c, 0xd4, 0xc7, 0xff, 0x55, 0x60, 0x60, 0xfd,
	0xdf, 0xa3, 0x04, 0xd0, 0xd0, 0xe6, 0x86, 0x6e, 0x3a, 0xe4, 0x11, 0x3d, 0x81, 0x9e, 0x3a, 0x5d,
	0x18, 0xa6, 0xb1, 0x72, 0x6c, 0xd5, 0xb1, 0x6c, 0xa2, 0x88, 0x03, 0xb7, 0x8d, 0xd5, 0x07, 0x77,
	0x65, 0xff, 0x42, 0x2a, 0xc2, 0x78, 0x61, 0x5d, 0x1a, 0x73, 0x9d, 0x54, 0x69, 0x03, 0x2a, 0x4b,
	0x8d, 0xd4, 0xe8, 0x19, 0xd0, 0x95, 0xee, 0x38, 0x73, 0x7d, 0xa1, 0x9b, 0x8e, 0x3b, 0xd5, 0x6d,
	0xe3, 0x17, 0x7d, 0x4a, 0xea, 0xf4, 0x09, 0x9c, 0x8a, 0x1d, 0x31, 0x4c, 0xec, 0xd0, 0xa3, 0xa2,
	0x21, 0xfa, 0x71, 0x71, 0x3d, 0x77, 0x0c, 0xd7, 0xb6, 0xae, 0x9d, 0xf2, 0xdc, 0x8e, 0xea, 0xa6,
	0x38, 0xae, 0xe5, 0x5c, 0xd5, 0xa4, 0xbb, 0xd5, 0x4c, 0xb5, 0x75, 0xd2, 0x12, 0x8d, 0x61, 0xeb,
	0xcb, 0x6b, 0x5b, 0x9b, 0xa9, 0x2b, 0x9d, 0xb4, 0x85, 0xac, 0x39, 0x4b, 0xf7, 0x7a, 0x39, 0xb7,
	0xd4, 0x29, 0x81, 0xcb, 0xb7, 0xff, 0x78, 0xb3, 0x0d, 0x8b, 0x9b, 0xfd, 0xfa, 0xc2, 0x4f, 0xe3,
	0x49, 0x1c, 0x26, 0x3c, 0xf3, 0xa2, 0x8c, 0xe7, 0x13, 0xfc, 0x75, 0xcc, 0x27, 0x79, 0xe6, 0x4f,
	0xb6, 0xe9, 0xa4, 0x1c, 0xc5, 0x75, 0x03, 0xf1, 0xcf, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x3b,
	0xe7, 0xb1, 0x0a, 0x68, 0x0a, 0x00, 0x00,
}
