// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goshare/rpc.proto

package goshare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	spider "github.com/mineralres/protos/src/go/spider"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 批量获取
type ReqGetInstrumentList struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetInstrumentList) Reset()         { *m = ReqGetInstrumentList{} }
func (m *ReqGetInstrumentList) String() string { return proto.CompactTextString(m) }
func (*ReqGetInstrumentList) ProtoMessage()    {}
func (*ReqGetInstrumentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{0}
}

func (m *ReqGetInstrumentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetInstrumentList.Unmarshal(m, b)
}
func (m *ReqGetInstrumentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetInstrumentList.Marshal(b, m, deterministic)
}
func (m *ReqGetInstrumentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetInstrumentList.Merge(m, src)
}
func (m *ReqGetInstrumentList) XXX_Size() int {
	return xxx_messageInfo_ReqGetInstrumentList.Size(m)
}
func (m *ReqGetInstrumentList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetInstrumentList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetInstrumentList proto.InternalMessageInfo

func (m *ReqGetInstrumentList) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type RspGetInstrumentList struct {
	List                 []*Instrument `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RspGetInstrumentList) Reset()         { *m = RspGetInstrumentList{} }
func (m *RspGetInstrumentList) String() string { return proto.CompactTextString(m) }
func (*RspGetInstrumentList) ProtoMessage()    {}
func (*RspGetInstrumentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{1}
}

func (m *RspGetInstrumentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGetInstrumentList.Unmarshal(m, b)
}
func (m *RspGetInstrumentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGetInstrumentList.Marshal(b, m, deterministic)
}
func (m *RspGetInstrumentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGetInstrumentList.Merge(m, src)
}
func (m *RspGetInstrumentList) XXX_Size() int {
	return xxx_messageInfo_RspGetInstrumentList.Size(m)
}
func (m *RspGetInstrumentList) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGetInstrumentList.DiscardUnknown(m)
}

var xxx_messageInfo_RspGetInstrumentList proto.InternalMessageInfo

func (m *RspGetInstrumentList) GetList() []*Instrument {
	if m != nil {
		return m.List
	}
	return nil
}

// 保存合约
type ReqSaveInstrument struct {
	Instrument           *Instrument `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReqSaveInstrument) Reset()         { *m = ReqSaveInstrument{} }
func (m *ReqSaveInstrument) String() string { return proto.CompactTextString(m) }
func (*ReqSaveInstrument) ProtoMessage()    {}
func (*ReqSaveInstrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{2}
}

func (m *ReqSaveInstrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSaveInstrument.Unmarshal(m, b)
}
func (m *ReqSaveInstrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSaveInstrument.Marshal(b, m, deterministic)
}
func (m *ReqSaveInstrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSaveInstrument.Merge(m, src)
}
func (m *ReqSaveInstrument) XXX_Size() int {
	return xxx_messageInfo_ReqSaveInstrument.Size(m)
}
func (m *ReqSaveInstrument) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSaveInstrument.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSaveInstrument proto.InternalMessageInfo

func (m *ReqSaveInstrument) GetInstrument() *Instrument {
	if m != nil {
		return m.Instrument
	}
	return nil
}

type RspSaveInstrument struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSaveInstrument) Reset()         { *m = RspSaveInstrument{} }
func (m *RspSaveInstrument) String() string { return proto.CompactTextString(m) }
func (*RspSaveInstrument) ProtoMessage()    {}
func (*RspSaveInstrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{3}
}

func (m *RspSaveInstrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSaveInstrument.Unmarshal(m, b)
}
func (m *RspSaveInstrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSaveInstrument.Marshal(b, m, deterministic)
}
func (m *RspSaveInstrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSaveInstrument.Merge(m, src)
}
func (m *RspSaveInstrument) XXX_Size() int {
	return xxx_messageInfo_RspSaveInstrument.Size(m)
}
func (m *RspSaveInstrument) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSaveInstrument.DiscardUnknown(m)
}

var xxx_messageInfo_RspSaveInstrument proto.InternalMessageInfo

// 读取合约
type ReqGetInstrument struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetInstrument) Reset()         { *m = ReqGetInstrument{} }
func (m *ReqGetInstrument) String() string { return proto.CompactTextString(m) }
func (*ReqGetInstrument) ProtoMessage()    {}
func (*ReqGetInstrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{4}
}

func (m *ReqGetInstrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetInstrument.Unmarshal(m, b)
}
func (m *ReqGetInstrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetInstrument.Marshal(b, m, deterministic)
}
func (m *ReqGetInstrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetInstrument.Merge(m, src)
}
func (m *ReqGetInstrument) XXX_Size() int {
	return xxx_messageInfo_ReqGetInstrument.Size(m)
}
func (m *ReqGetInstrument) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetInstrument.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetInstrument proto.InternalMessageInfo

func (m *ReqGetInstrument) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqGetInstrument) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type RspGetInstrument struct {
	Instrument           *Instrument `protobuf:"bytes,1,opt,name=instrument,proto3" json:"instrument"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RspGetInstrument) Reset()         { *m = RspGetInstrument{} }
func (m *RspGetInstrument) String() string { return proto.CompactTextString(m) }
func (*RspGetInstrument) ProtoMessage()    {}
func (*RspGetInstrument) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{5}
}

func (m *RspGetInstrument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGetInstrument.Unmarshal(m, b)
}
func (m *RspGetInstrument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGetInstrument.Marshal(b, m, deterministic)
}
func (m *RspGetInstrument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGetInstrument.Merge(m, src)
}
func (m *RspGetInstrument) XXX_Size() int {
	return xxx_messageInfo_RspGetInstrument.Size(m)
}
func (m *RspGetInstrument) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGetInstrument.DiscardUnknown(m)
}

var xxx_messageInfo_RspGetInstrument proto.InternalMessageInfo

func (m *RspGetInstrument) GetInstrument() *Instrument {
	if m != nil {
		return m.Instrument
	}
	return nil
}

type ReqSubscribe struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	List                 []string `protobuf:"bytes,3,rep,name=list,proto3" json:"list"`
	BinaryData           bool     `protobuf:"varint,4,opt,name=binary_data,json=binaryData,proto3" json:"binaryData"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSubscribe) Reset()         { *m = ReqSubscribe{} }
func (m *ReqSubscribe) String() string { return proto.CompactTextString(m) }
func (*ReqSubscribe) ProtoMessage()    {}
func (*ReqSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{6}
}

func (m *ReqSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSubscribe.Unmarshal(m, b)
}
func (m *ReqSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSubscribe.Marshal(b, m, deterministic)
}
func (m *ReqSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSubscribe.Merge(m, src)
}
func (m *ReqSubscribe) XXX_Size() int {
	return xxx_messageInfo_ReqSubscribe.Size(m)
}
func (m *ReqSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSubscribe proto.InternalMessageInfo

func (m *ReqSubscribe) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqSubscribe) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqSubscribe) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReqSubscribe) GetBinaryData() bool {
	if m != nil {
		return m.BinaryData
	}
	return false
}

type RspSubscribe struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSubscribe) Reset()         { *m = RspSubscribe{} }
func (m *RspSubscribe) String() string { return proto.CompactTextString(m) }
func (*RspSubscribe) ProtoMessage()    {}
func (*RspSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{7}
}

func (m *RspSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSubscribe.Unmarshal(m, b)
}
func (m *RspSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSubscribe.Marshal(b, m, deterministic)
}
func (m *RspSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSubscribe.Merge(m, src)
}
func (m *RspSubscribe) XXX_Size() int {
	return xxx_messageInfo_RspSubscribe.Size(m)
}
func (m *RspSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_RspSubscribe proto.InternalMessageInfo

type ReqUnSubscribe struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	List                 []string `protobuf:"bytes,2,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUnSubscribe) Reset()         { *m = ReqUnSubscribe{} }
func (m *ReqUnSubscribe) String() string { return proto.CompactTextString(m) }
func (*ReqUnSubscribe) ProtoMessage()    {}
func (*ReqUnSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{8}
}

func (m *ReqUnSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUnSubscribe.Unmarshal(m, b)
}
func (m *ReqUnSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUnSubscribe.Marshal(b, m, deterministic)
}
func (m *ReqUnSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUnSubscribe.Merge(m, src)
}
func (m *ReqUnSubscribe) XXX_Size() int {
	return xxx_messageInfo_ReqUnSubscribe.Size(m)
}
func (m *ReqUnSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUnSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUnSubscribe proto.InternalMessageInfo

func (m *ReqUnSubscribe) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqUnSubscribe) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type RspUnSubscribe struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspUnSubscribe) Reset()         { *m = RspUnSubscribe{} }
func (m *RspUnSubscribe) String() string { return proto.CompactTextString(m) }
func (*RspUnSubscribe) ProtoMessage()    {}
func (*RspUnSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{9}
}

func (m *RspUnSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspUnSubscribe.Unmarshal(m, b)
}
func (m *RspUnSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspUnSubscribe.Marshal(b, m, deterministic)
}
func (m *RspUnSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspUnSubscribe.Merge(m, src)
}
func (m *RspUnSubscribe) XXX_Size() int {
	return xxx_messageInfo_RspUnSubscribe.Size(m)
}
func (m *RspUnSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_RspUnSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_RspUnSubscribe proto.InternalMessageInfo

type ReqCombineSubscribe struct {
	Exchange             string       `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string       `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	PeriodList           []PeriodType `protobuf:"varint,3,rep,packed,name=period_list,json=periodList,proto3,enum=goshare.PeriodType" json:"periodList"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReqCombineSubscribe) Reset()         { *m = ReqCombineSubscribe{} }
func (m *ReqCombineSubscribe) String() string { return proto.CompactTextString(m) }
func (*ReqCombineSubscribe) ProtoMessage()    {}
func (*ReqCombineSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{10}
}

func (m *ReqCombineSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCombineSubscribe.Unmarshal(m, b)
}
func (m *ReqCombineSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCombineSubscribe.Marshal(b, m, deterministic)
}
func (m *ReqCombineSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCombineSubscribe.Merge(m, src)
}
func (m *ReqCombineSubscribe) XXX_Size() int {
	return xxx_messageInfo_ReqCombineSubscribe.Size(m)
}
func (m *ReqCombineSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCombineSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCombineSubscribe proto.InternalMessageInfo

func (m *ReqCombineSubscribe) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqCombineSubscribe) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqCombineSubscribe) GetPeriodList() []PeriodType {
	if m != nil {
		return m.PeriodList
	}
	return nil
}

type RspCombineSubscribe struct {
	Exchange             string              `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string              `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	History              []*KlineSeries      `protobuf:"bytes,3,rep,name=history,proto3" json:"history"`
	Tick                 *MarketDataSnapshot `protobuf:"bytes,4,opt,name=tick,proto3" json:"tick"`
	Klines               []*Kline            `protobuf:"bytes,5,rep,name=klines,proto3" json:"klines"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *RspCombineSubscribe) Reset()         { *m = RspCombineSubscribe{} }
func (m *RspCombineSubscribe) String() string { return proto.CompactTextString(m) }
func (*RspCombineSubscribe) ProtoMessage()    {}
func (*RspCombineSubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{11}
}

func (m *RspCombineSubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspCombineSubscribe.Unmarshal(m, b)
}
func (m *RspCombineSubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspCombineSubscribe.Marshal(b, m, deterministic)
}
func (m *RspCombineSubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspCombineSubscribe.Merge(m, src)
}
func (m *RspCombineSubscribe) XXX_Size() int {
	return xxx_messageInfo_RspCombineSubscribe.Size(m)
}
func (m *RspCombineSubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_RspCombineSubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_RspCombineSubscribe proto.InternalMessageInfo

func (m *RspCombineSubscribe) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *RspCombineSubscribe) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *RspCombineSubscribe) GetHistory() []*KlineSeries {
	if m != nil {
		return m.History
	}
	return nil
}

func (m *RspCombineSubscribe) GetTick() *MarketDataSnapshot {
	if m != nil {
		return m.Tick
	}
	return nil
}

func (m *RspCombineSubscribe) GetKlines() []*Kline {
	if m != nil {
		return m.Klines
	}
	return nil
}

type ReqGetTickSeries struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Start                int32    `protobuf:"varint,3,opt,name=start,proto3" json:"start"`
	End                  int32    `protobuf:"varint,4,opt,name=end,proto3" json:"end"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetTickSeries) Reset()         { *m = ReqGetTickSeries{} }
func (m *ReqGetTickSeries) String() string { return proto.CompactTextString(m) }
func (*ReqGetTickSeries) ProtoMessage()    {}
func (*ReqGetTickSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{12}
}

func (m *ReqGetTickSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetTickSeries.Unmarshal(m, b)
}
func (m *ReqGetTickSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetTickSeries.Marshal(b, m, deterministic)
}
func (m *ReqGetTickSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetTickSeries.Merge(m, src)
}
func (m *ReqGetTickSeries) XXX_Size() int {
	return xxx_messageInfo_ReqGetTickSeries.Size(m)
}
func (m *ReqGetTickSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetTickSeries.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetTickSeries proto.InternalMessageInfo

func (m *ReqGetTickSeries) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqGetTickSeries) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqGetTickSeries) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ReqGetTickSeries) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

type RspGetTickSeries struct {
	Exchange             string                `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string                `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Start                int32                 `protobuf:"varint,3,opt,name=start,proto3" json:"start"`
	End                  int32                 `protobuf:"varint,4,opt,name=end,proto3" json:"end"`
	List                 []*MarketDataSnapshot `protobuf:"bytes,5,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *RspGetTickSeries) Reset()         { *m = RspGetTickSeries{} }
func (m *RspGetTickSeries) String() string { return proto.CompactTextString(m) }
func (*RspGetTickSeries) ProtoMessage()    {}
func (*RspGetTickSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{13}
}

func (m *RspGetTickSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGetTickSeries.Unmarshal(m, b)
}
func (m *RspGetTickSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGetTickSeries.Marshal(b, m, deterministic)
}
func (m *RspGetTickSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGetTickSeries.Merge(m, src)
}
func (m *RspGetTickSeries) XXX_Size() int {
	return xxx_messageInfo_RspGetTickSeries.Size(m)
}
func (m *RspGetTickSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGetTickSeries.DiscardUnknown(m)
}

var xxx_messageInfo_RspGetTickSeries proto.InternalMessageInfo

func (m *RspGetTickSeries) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *RspGetTickSeries) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *RspGetTickSeries) GetStart() int32 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *RspGetTickSeries) GetEnd() int32 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *RspGetTickSeries) GetList() []*MarketDataSnapshot {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqSaveKlineSeries struct {
	Exchange             string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Period               PeriodType      `protobuf:"varint,3,opt,name=period,proto3,enum=goshare.PeriodType" json:"period"`
	Adjust               PriceAdjustType `protobuf:"varint,4,opt,name=adjust,proto3,enum=goshare.PriceAdjustType" json:"adjust"`
	List                 []*Kline        `protobuf:"bytes,5,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqSaveKlineSeries) Reset()         { *m = ReqSaveKlineSeries{} }
func (m *ReqSaveKlineSeries) String() string { return proto.CompactTextString(m) }
func (*ReqSaveKlineSeries) ProtoMessage()    {}
func (*ReqSaveKlineSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{14}
}

func (m *ReqSaveKlineSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSaveKlineSeries.Unmarshal(m, b)
}
func (m *ReqSaveKlineSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSaveKlineSeries.Marshal(b, m, deterministic)
}
func (m *ReqSaveKlineSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSaveKlineSeries.Merge(m, src)
}
func (m *ReqSaveKlineSeries) XXX_Size() int {
	return xxx_messageInfo_ReqSaveKlineSeries.Size(m)
}
func (m *ReqSaveKlineSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSaveKlineSeries.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSaveKlineSeries proto.InternalMessageInfo

func (m *ReqSaveKlineSeries) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqSaveKlineSeries) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqSaveKlineSeries) GetPeriod() PeriodType {
	if m != nil {
		return m.Period
	}
	return PeriodType_TICK
}

func (m *ReqSaveKlineSeries) GetAdjust() PriceAdjustType {
	if m != nil {
		return m.Adjust
	}
	return PriceAdjustType_NORMAL
}

func (m *ReqSaveKlineSeries) GetList() []*Kline {
	if m != nil {
		return m.List
	}
	return nil
}

type RspSaveKlineSeries struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSaveKlineSeries) Reset()         { *m = RspSaveKlineSeries{} }
func (m *RspSaveKlineSeries) String() string { return proto.CompactTextString(m) }
func (*RspSaveKlineSeries) ProtoMessage()    {}
func (*RspSaveKlineSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{15}
}

func (m *RspSaveKlineSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSaveKlineSeries.Unmarshal(m, b)
}
func (m *RspSaveKlineSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSaveKlineSeries.Marshal(b, m, deterministic)
}
func (m *RspSaveKlineSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSaveKlineSeries.Merge(m, src)
}
func (m *RspSaveKlineSeries) XXX_Size() int {
	return xxx_messageInfo_RspSaveKlineSeries.Size(m)
}
func (m *RspSaveKlineSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSaveKlineSeries.DiscardUnknown(m)
}

var xxx_messageInfo_RspSaveKlineSeries proto.InternalMessageInfo

type ReqGetKlineSeries struct {
	Exchange             string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Period               PeriodType      `protobuf:"varint,3,opt,name=period,proto3,enum=goshare.PeriodType" json:"period"`
	Adjust               PriceAdjustType `protobuf:"varint,4,opt,name=adjust,proto3,enum=goshare.PriceAdjustType" json:"adjust"`
	Start                int64           `protobuf:"varint,5,opt,name=start,proto3" json:"start"`
	Count                int32           `protobuf:"varint,6,opt,name=count,proto3" json:"count"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqGetKlineSeries) Reset()         { *m = ReqGetKlineSeries{} }
func (m *ReqGetKlineSeries) String() string { return proto.CompactTextString(m) }
func (*ReqGetKlineSeries) ProtoMessage()    {}
func (*ReqGetKlineSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{16}
}

func (m *ReqGetKlineSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetKlineSeries.Unmarshal(m, b)
}
func (m *ReqGetKlineSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetKlineSeries.Marshal(b, m, deterministic)
}
func (m *ReqGetKlineSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetKlineSeries.Merge(m, src)
}
func (m *ReqGetKlineSeries) XXX_Size() int {
	return xxx_messageInfo_ReqGetKlineSeries.Size(m)
}
func (m *ReqGetKlineSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetKlineSeries.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetKlineSeries proto.InternalMessageInfo

func (m *ReqGetKlineSeries) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqGetKlineSeries) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqGetKlineSeries) GetPeriod() PeriodType {
	if m != nil {
		return m.Period
	}
	return PeriodType_TICK
}

func (m *ReqGetKlineSeries) GetAdjust() PriceAdjustType {
	if m != nil {
		return m.Adjust
	}
	return PriceAdjustType_NORMAL
}

func (m *ReqGetKlineSeries) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *ReqGetKlineSeries) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type RspGetKlineSeries struct {
	Exchange             string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Period               PeriodType      `protobuf:"varint,3,opt,name=period,proto3,enum=goshare.PeriodType" json:"period"`
	Adjust               PriceAdjustType `protobuf:"varint,4,opt,name=adjust,proto3,enum=goshare.PriceAdjustType" json:"adjust"`
	List                 []*Kline        `protobuf:"bytes,5,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RspGetKlineSeries) Reset()         { *m = RspGetKlineSeries{} }
func (m *RspGetKlineSeries) String() string { return proto.CompactTextString(m) }
func (*RspGetKlineSeries) ProtoMessage()    {}
func (*RspGetKlineSeries) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{17}
}

func (m *RspGetKlineSeries) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGetKlineSeries.Unmarshal(m, b)
}
func (m *RspGetKlineSeries) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGetKlineSeries.Marshal(b, m, deterministic)
}
func (m *RspGetKlineSeries) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGetKlineSeries.Merge(m, src)
}
func (m *RspGetKlineSeries) XXX_Size() int {
	return xxx_messageInfo_RspGetKlineSeries.Size(m)
}
func (m *RspGetKlineSeries) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGetKlineSeries.DiscardUnknown(m)
}

var xxx_messageInfo_RspGetKlineSeries proto.InternalMessageInfo

func (m *RspGetKlineSeries) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *RspGetKlineSeries) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *RspGetKlineSeries) GetPeriod() PeriodType {
	if m != nil {
		return m.Period
	}
	return PeriodType_TICK
}

func (m *RspGetKlineSeries) GetAdjust() PriceAdjustType {
	if m != nil {
		return m.Adjust
	}
	return PriceAdjustType_NORMAL
}

func (m *RspGetKlineSeries) GetList() []*Kline {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqSSEStockOptionList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSSEStockOptionList) Reset()         { *m = ReqSSEStockOptionList{} }
func (m *ReqSSEStockOptionList) String() string { return proto.CompactTextString(m) }
func (*ReqSSEStockOptionList) ProtoMessage()    {}
func (*ReqSSEStockOptionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{18}
}

func (m *ReqSSEStockOptionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSSEStockOptionList.Unmarshal(m, b)
}
func (m *ReqSSEStockOptionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSSEStockOptionList.Marshal(b, m, deterministic)
}
func (m *ReqSSEStockOptionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSSEStockOptionList.Merge(m, src)
}
func (m *ReqSSEStockOptionList) XXX_Size() int {
	return xxx_messageInfo_ReqSSEStockOptionList.Size(m)
}
func (m *ReqSSEStockOptionList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSSEStockOptionList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSSEStockOptionList proto.InternalMessageInfo

type RspSSEStockOptionList struct {
	List                 []*spider.SSEStockOption `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *RspSSEStockOptionList) Reset()         { *m = RspSSEStockOptionList{} }
func (m *RspSSEStockOptionList) String() string { return proto.CompactTextString(m) }
func (*RspSSEStockOptionList) ProtoMessage()    {}
func (*RspSSEStockOptionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{19}
}

func (m *RspSSEStockOptionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSSEStockOptionList.Unmarshal(m, b)
}
func (m *RspSSEStockOptionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSSEStockOptionList.Marshal(b, m, deterministic)
}
func (m *RspSSEStockOptionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSSEStockOptionList.Merge(m, src)
}
func (m *RspSSEStockOptionList) XXX_Size() int {
	return xxx_messageInfo_RspSSEStockOptionList.Size(m)
}
func (m *RspSSEStockOptionList) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSSEStockOptionList.DiscardUnknown(m)
}

var xxx_messageInfo_RspSSEStockOptionList proto.InternalMessageInfo

func (m *RspSSEStockOptionList) GetList() []*spider.SSEStockOption {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqSaveBonusHistory struct {
	Exchange             string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	List                 []*spider.Bonus `protobuf:"bytes,3,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqSaveBonusHistory) Reset()         { *m = ReqSaveBonusHistory{} }
func (m *ReqSaveBonusHistory) String() string { return proto.CompactTextString(m) }
func (*ReqSaveBonusHistory) ProtoMessage()    {}
func (*ReqSaveBonusHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{20}
}

func (m *ReqSaveBonusHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSaveBonusHistory.Unmarshal(m, b)
}
func (m *ReqSaveBonusHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSaveBonusHistory.Marshal(b, m, deterministic)
}
func (m *ReqSaveBonusHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSaveBonusHistory.Merge(m, src)
}
func (m *ReqSaveBonusHistory) XXX_Size() int {
	return xxx_messageInfo_ReqSaveBonusHistory.Size(m)
}
func (m *ReqSaveBonusHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSaveBonusHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSaveBonusHistory proto.InternalMessageInfo

func (m *ReqSaveBonusHistory) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqSaveBonusHistory) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *ReqSaveBonusHistory) GetList() []*spider.Bonus {
	if m != nil {
		return m.List
	}
	return nil
}

type RspSaveBonusHistory struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSaveBonusHistory) Reset()         { *m = RspSaveBonusHistory{} }
func (m *RspSaveBonusHistory) String() string { return proto.CompactTextString(m) }
func (*RspSaveBonusHistory) ProtoMessage()    {}
func (*RspSaveBonusHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{21}
}

func (m *RspSaveBonusHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSaveBonusHistory.Unmarshal(m, b)
}
func (m *RspSaveBonusHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSaveBonusHistory.Marshal(b, m, deterministic)
}
func (m *RspSaveBonusHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSaveBonusHistory.Merge(m, src)
}
func (m *RspSaveBonusHistory) XXX_Size() int {
	return xxx_messageInfo_RspSaveBonusHistory.Size(m)
}
func (m *RspSaveBonusHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSaveBonusHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RspSaveBonusHistory proto.InternalMessageInfo

type ReqGetBonusHistory struct {
	Exchange             string   `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGetBonusHistory) Reset()         { *m = ReqGetBonusHistory{} }
func (m *ReqGetBonusHistory) String() string { return proto.CompactTextString(m) }
func (*ReqGetBonusHistory) ProtoMessage()    {}
func (*ReqGetBonusHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{22}
}

func (m *ReqGetBonusHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGetBonusHistory.Unmarshal(m, b)
}
func (m *ReqGetBonusHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGetBonusHistory.Marshal(b, m, deterministic)
}
func (m *ReqGetBonusHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGetBonusHistory.Merge(m, src)
}
func (m *ReqGetBonusHistory) XXX_Size() int {
	return xxx_messageInfo_ReqGetBonusHistory.Size(m)
}
func (m *ReqGetBonusHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGetBonusHistory.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGetBonusHistory proto.InternalMessageInfo

func (m *ReqGetBonusHistory) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ReqGetBonusHistory) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

type RspGetBonusHistory struct {
	Exchange             string          `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string          `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	List                 []*spider.Bonus `protobuf:"bytes,3,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RspGetBonusHistory) Reset()         { *m = RspGetBonusHistory{} }
func (m *RspGetBonusHistory) String() string { return proto.CompactTextString(m) }
func (*RspGetBonusHistory) ProtoMessage()    {}
func (*RspGetBonusHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{23}
}

func (m *RspGetBonusHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGetBonusHistory.Unmarshal(m, b)
}
func (m *RspGetBonusHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGetBonusHistory.Marshal(b, m, deterministic)
}
func (m *RspGetBonusHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGetBonusHistory.Merge(m, src)
}
func (m *RspGetBonusHistory) XXX_Size() int {
	return xxx_messageInfo_RspGetBonusHistory.Size(m)
}
func (m *RspGetBonusHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGetBonusHistory.DiscardUnknown(m)
}

var xxx_messageInfo_RspGetBonusHistory proto.InternalMessageInfo

func (m *RspGetBonusHistory) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *RspGetBonusHistory) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *RspGetBonusHistory) GetList() []*spider.Bonus {
	if m != nil {
		return m.List
	}
	return nil
}

type ReqBatchDelete struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBatchDelete) Reset()         { *m = ReqBatchDelete{} }
func (m *ReqBatchDelete) String() string { return proto.CompactTextString(m) }
func (*ReqBatchDelete) ProtoMessage()    {}
func (*ReqBatchDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{24}
}

func (m *ReqBatchDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBatchDelete.Unmarshal(m, b)
}
func (m *ReqBatchDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBatchDelete.Marshal(b, m, deterministic)
}
func (m *ReqBatchDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBatchDelete.Merge(m, src)
}
func (m *ReqBatchDelete) XXX_Size() int {
	return xxx_messageInfo_ReqBatchDelete.Size(m)
}
func (m *ReqBatchDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBatchDelete.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBatchDelete proto.InternalMessageInfo

func (m *ReqBatchDelete) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type RspBatchDelete struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspBatchDelete) Reset()         { *m = RspBatchDelete{} }
func (m *RspBatchDelete) String() string { return proto.CompactTextString(m) }
func (*RspBatchDelete) ProtoMessage()    {}
func (*RspBatchDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{25}
}

func (m *RspBatchDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspBatchDelete.Unmarshal(m, b)
}
func (m *RspBatchDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspBatchDelete.Marshal(b, m, deterministic)
}
func (m *RspBatchDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspBatchDelete.Merge(m, src)
}
func (m *RspBatchDelete) XXX_Size() int {
	return xxx_messageInfo_RspBatchDelete.Size(m)
}
func (m *RspBatchDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_RspBatchDelete.DiscardUnknown(m)
}

var xxx_messageInfo_RspBatchDelete proto.InternalMessageInfo

type ReqBatchGet struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBatchGet) Reset()         { *m = ReqBatchGet{} }
func (m *ReqBatchGet) String() string { return proto.CompactTextString(m) }
func (*ReqBatchGet) ProtoMessage()    {}
func (*ReqBatchGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{26}
}

func (m *ReqBatchGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBatchGet.Unmarshal(m, b)
}
func (m *ReqBatchGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBatchGet.Marshal(b, m, deterministic)
}
func (m *ReqBatchGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBatchGet.Merge(m, src)
}
func (m *ReqBatchGet) XXX_Size() int {
	return xxx_messageInfo_ReqBatchGet.Size(m)
}
func (m *ReqBatchGet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBatchGet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBatchGet proto.InternalMessageInfo

func (m *ReqBatchGet) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

type RspBatchGet struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspBatchGet) Reset()         { *m = RspBatchGet{} }
func (m *RspBatchGet) String() string { return proto.CompactTextString(m) }
func (*RspBatchGet) ProtoMessage()    {}
func (*RspBatchGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{27}
}

func (m *RspBatchGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspBatchGet.Unmarshal(m, b)
}
func (m *RspBatchGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspBatchGet.Marshal(b, m, deterministic)
}
func (m *RspBatchGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspBatchGet.Merge(m, src)
}
func (m *RspBatchGet) XXX_Size() int {
	return xxx_messageInfo_RspBatchGet.Size(m)
}
func (m *RspBatchGet) XXX_DiscardUnknown() {
	xxx_messageInfo_RspBatchGet.DiscardUnknown(m)
}

var xxx_messageInfo_RspBatchGet proto.InternalMessageInfo

func (m *RspBatchGet) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type ReqBatchPut struct {
	Keys                 [][]byte `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys"`
	Values               [][]byte `protobuf:"bytes,2,rep,name=values,proto3" json:"values"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBatchPut) Reset()         { *m = ReqBatchPut{} }
func (m *ReqBatchPut) String() string { return proto.CompactTextString(m) }
func (*ReqBatchPut) ProtoMessage()    {}
func (*ReqBatchPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{28}
}

func (m *ReqBatchPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBatchPut.Unmarshal(m, b)
}
func (m *ReqBatchPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBatchPut.Marshal(b, m, deterministic)
}
func (m *ReqBatchPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBatchPut.Merge(m, src)
}
func (m *ReqBatchPut) XXX_Size() int {
	return xxx_messageInfo_ReqBatchPut.Size(m)
}
func (m *ReqBatchPut) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBatchPut.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBatchPut proto.InternalMessageInfo

func (m *ReqBatchPut) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *ReqBatchPut) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type RspBatchPut struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspBatchPut) Reset()         { *m = RspBatchPut{} }
func (m *RspBatchPut) String() string { return proto.CompactTextString(m) }
func (*RspBatchPut) ProtoMessage()    {}
func (*RspBatchPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{29}
}

func (m *RspBatchPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspBatchPut.Unmarshal(m, b)
}
func (m *RspBatchPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspBatchPut.Marshal(b, m, deterministic)
}
func (m *RspBatchPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspBatchPut.Merge(m, src)
}
func (m *RspBatchPut) XXX_Size() int {
	return xxx_messageInfo_RspBatchPut.Size(m)
}
func (m *RspBatchPut) XXX_DiscardUnknown() {
	xxx_messageInfo_RspBatchPut.DiscardUnknown(m)
}

var xxx_messageInfo_RspBatchPut proto.InternalMessageInfo

type ReqDelete struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDelete) Reset()         { *m = ReqDelete{} }
func (m *ReqDelete) String() string { return proto.CompactTextString(m) }
func (*ReqDelete) ProtoMessage()    {}
func (*ReqDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{30}
}

func (m *ReqDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDelete.Unmarshal(m, b)
}
func (m *ReqDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDelete.Marshal(b, m, deterministic)
}
func (m *ReqDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDelete.Merge(m, src)
}
func (m *ReqDelete) XXX_Size() int {
	return xxx_messageInfo_ReqDelete.Size(m)
}
func (m *ReqDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDelete.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDelete proto.InternalMessageInfo

func (m *ReqDelete) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type RspDelete struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspDelete) Reset()         { *m = RspDelete{} }
func (m *RspDelete) String() string { return proto.CompactTextString(m) }
func (*RspDelete) ProtoMessage()    {}
func (*RspDelete) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{31}
}

func (m *RspDelete) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspDelete.Unmarshal(m, b)
}
func (m *RspDelete) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspDelete.Marshal(b, m, deterministic)
}
func (m *RspDelete) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspDelete.Merge(m, src)
}
func (m *RspDelete) XXX_Size() int {
	return xxx_messageInfo_RspDelete.Size(m)
}
func (m *RspDelete) XXX_DiscardUnknown() {
	xxx_messageInfo_RspDelete.DiscardUnknown(m)
}

var xxx_messageInfo_RspDelete proto.InternalMessageInfo

type ReqGet struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqGet) Reset()         { *m = ReqGet{} }
func (m *ReqGet) String() string { return proto.CompactTextString(m) }
func (*ReqGet) ProtoMessage()    {}
func (*ReqGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{32}
}

func (m *ReqGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqGet.Unmarshal(m, b)
}
func (m *ReqGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqGet.Marshal(b, m, deterministic)
}
func (m *ReqGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqGet.Merge(m, src)
}
func (m *ReqGet) XXX_Size() int {
	return xxx_messageInfo_ReqGet.Size(m)
}
func (m *ReqGet) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqGet.DiscardUnknown(m)
}

var xxx_messageInfo_ReqGet proto.InternalMessageInfo

func (m *ReqGet) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type RspGet struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value"`
	NotFound             bool     `protobuf:"varint,2,opt,name=not_found,json=notFound,proto3" json:"notFound"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspGet) Reset()         { *m = RspGet{} }
func (m *RspGet) String() string { return proto.CompactTextString(m) }
func (*RspGet) ProtoMessage()    {}
func (*RspGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{33}
}

func (m *RspGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspGet.Unmarshal(m, b)
}
func (m *RspGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspGet.Marshal(b, m, deterministic)
}
func (m *RspGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspGet.Merge(m, src)
}
func (m *RspGet) XXX_Size() int {
	return xxx_messageInfo_RspGet.Size(m)
}
func (m *RspGet) XXX_DiscardUnknown() {
	xxx_messageInfo_RspGet.DiscardUnknown(m)
}

var xxx_messageInfo_RspGet proto.InternalMessageInfo

func (m *RspGet) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *RspGet) GetNotFound() bool {
	if m != nil {
		return m.NotFound
	}
	return false
}

type ReqPut struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPut) Reset()         { *m = ReqPut{} }
func (m *ReqPut) String() string { return proto.CompactTextString(m) }
func (*ReqPut) ProtoMessage()    {}
func (*ReqPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{34}
}

func (m *ReqPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPut.Unmarshal(m, b)
}
func (m *ReqPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPut.Marshal(b, m, deterministic)
}
func (m *ReqPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPut.Merge(m, src)
}
func (m *ReqPut) XXX_Size() int {
	return xxx_messageInfo_ReqPut.Size(m)
}
func (m *ReqPut) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPut.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPut proto.InternalMessageInfo

func (m *ReqPut) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReqPut) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RspPut struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspPut) Reset()         { *m = RspPut{} }
func (m *RspPut) String() string { return proto.CompactTextString(m) }
func (*RspPut) ProtoMessage()    {}
func (*RspPut) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{35}
}

func (m *RspPut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspPut.Unmarshal(m, b)
}
func (m *RspPut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspPut.Marshal(b, m, deterministic)
}
func (m *RspPut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspPut.Merge(m, src)
}
func (m *RspPut) XXX_Size() int {
	return xxx_messageInfo_RspPut.Size(m)
}
func (m *RspPut) XXX_DiscardUnknown() {
	xxx_messageInfo_RspPut.DiscardUnknown(m)
}

var xxx_messageInfo_RspPut proto.InternalMessageInfo

type ReqReverseScan struct {
	Start                []byte   `protobuf:"bytes,1,opt,name=start,proto3" json:"start"`
	End                  []byte   `protobuf:"bytes,2,opt,name=end,proto3" json:"end"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqReverseScan) Reset()         { *m = ReqReverseScan{} }
func (m *ReqReverseScan) String() string { return proto.CompactTextString(m) }
func (*ReqReverseScan) ProtoMessage()    {}
func (*ReqReverseScan) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{36}
}

func (m *ReqReverseScan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqReverseScan.Unmarshal(m, b)
}
func (m *ReqReverseScan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqReverseScan.Marshal(b, m, deterministic)
}
func (m *ReqReverseScan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqReverseScan.Merge(m, src)
}
func (m *ReqReverseScan) XXX_Size() int {
	return xxx_messageInfo_ReqReverseScan.Size(m)
}
func (m *ReqReverseScan) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqReverseScan.DiscardUnknown(m)
}

var xxx_messageInfo_ReqReverseScan proto.InternalMessageInfo

func (m *ReqReverseScan) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ReqReverseScan) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ReqReverseScan) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RspReverseScan struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspReverseScan) Reset()         { *m = RspReverseScan{} }
func (m *RspReverseScan) String() string { return proto.CompactTextString(m) }
func (*RspReverseScan) ProtoMessage()    {}
func (*RspReverseScan) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{37}
}

func (m *RspReverseScan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspReverseScan.Unmarshal(m, b)
}
func (m *RspReverseScan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspReverseScan.Marshal(b, m, deterministic)
}
func (m *RspReverseScan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspReverseScan.Merge(m, src)
}
func (m *RspReverseScan) XXX_Size() int {
	return xxx_messageInfo_RspReverseScan.Size(m)
}
func (m *RspReverseScan) XXX_DiscardUnknown() {
	xxx_messageInfo_RspReverseScan.DiscardUnknown(m)
}

var xxx_messageInfo_RspReverseScan proto.InternalMessageInfo

func (m *RspReverseScan) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

type ReqScan struct {
	Start                []byte   `protobuf:"bytes,1,opt,name=start,proto3" json:"start"`
	End                  []byte   `protobuf:"bytes,2,opt,name=end,proto3" json:"end"`
	Limit                int32    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqScan) Reset()         { *m = ReqScan{} }
func (m *ReqScan) String() string { return proto.CompactTextString(m) }
func (*ReqScan) ProtoMessage()    {}
func (*ReqScan) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{38}
}

func (m *ReqScan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqScan.Unmarshal(m, b)
}
func (m *ReqScan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqScan.Marshal(b, m, deterministic)
}
func (m *ReqScan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqScan.Merge(m, src)
}
func (m *ReqScan) XXX_Size() int {
	return xxx_messageInfo_ReqScan.Size(m)
}
func (m *ReqScan) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqScan.DiscardUnknown(m)
}

var xxx_messageInfo_ReqScan proto.InternalMessageInfo

func (m *ReqScan) GetStart() []byte {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *ReqScan) GetEnd() []byte {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *ReqScan) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type RspScan struct {
	Values               [][]byte `protobuf:"bytes,1,rep,name=values,proto3" json:"values"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspScan) Reset()         { *m = RspScan{} }
func (m *RspScan) String() string { return proto.CompactTextString(m) }
func (*RspScan) ProtoMessage()    {}
func (*RspScan) Descriptor() ([]byte, []int) {
	return fileDescriptor_49c3d35f07f60759, []int{39}
}

func (m *RspScan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspScan.Unmarshal(m, b)
}
func (m *RspScan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspScan.Marshal(b, m, deterministic)
}
func (m *RspScan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspScan.Merge(m, src)
}
func (m *RspScan) XXX_Size() int {
	return xxx_messageInfo_RspScan.Size(m)
}
func (m *RspScan) XXX_DiscardUnknown() {
	xxx_messageInfo_RspScan.DiscardUnknown(m)
}

var xxx_messageInfo_RspScan proto.InternalMessageInfo

func (m *RspScan) GetValues() [][]byte {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*ReqGetInstrumentList)(nil), "goshare.ReqGetInstrumentList")
	proto.RegisterType((*RspGetInstrumentList)(nil), "goshare.RspGetInstrumentList")
	proto.RegisterType((*ReqSaveInstrument)(nil), "goshare.ReqSaveInstrument")
	proto.RegisterType((*RspSaveInstrument)(nil), "goshare.RspSaveInstrument")
	proto.RegisterType((*ReqGetInstrument)(nil), "goshare.ReqGetInstrument")
	proto.RegisterType((*RspGetInstrument)(nil), "goshare.RspGetInstrument")
	proto.RegisterType((*ReqSubscribe)(nil), "goshare.ReqSubscribe")
	proto.RegisterType((*RspSubscribe)(nil), "goshare.RspSubscribe")
	proto.RegisterType((*ReqUnSubscribe)(nil), "goshare.ReqUnSubscribe")
	proto.RegisterType((*RspUnSubscribe)(nil), "goshare.RspUnSubscribe")
	proto.RegisterType((*ReqCombineSubscribe)(nil), "goshare.ReqCombineSubscribe")
	proto.RegisterType((*RspCombineSubscribe)(nil), "goshare.RspCombineSubscribe")
	proto.RegisterType((*ReqGetTickSeries)(nil), "goshare.ReqGetTickSeries")
	proto.RegisterType((*RspGetTickSeries)(nil), "goshare.RspGetTickSeries")
	proto.RegisterType((*ReqSaveKlineSeries)(nil), "goshare.ReqSaveKlineSeries")
	proto.RegisterType((*RspSaveKlineSeries)(nil), "goshare.RspSaveKlineSeries")
	proto.RegisterType((*ReqGetKlineSeries)(nil), "goshare.ReqGetKlineSeries")
	proto.RegisterType((*RspGetKlineSeries)(nil), "goshare.RspGetKlineSeries")
	proto.RegisterType((*ReqSSEStockOptionList)(nil), "goshare.ReqSSEStockOptionList")
	proto.RegisterType((*RspSSEStockOptionList)(nil), "goshare.RspSSEStockOptionList")
	proto.RegisterType((*ReqSaveBonusHistory)(nil), "goshare.ReqSaveBonusHistory")
	proto.RegisterType((*RspSaveBonusHistory)(nil), "goshare.RspSaveBonusHistory")
	proto.RegisterType((*ReqGetBonusHistory)(nil), "goshare.ReqGetBonusHistory")
	proto.RegisterType((*RspGetBonusHistory)(nil), "goshare.RspGetBonusHistory")
	proto.RegisterType((*ReqBatchDelete)(nil), "goshare.ReqBatchDelete")
	proto.RegisterType((*RspBatchDelete)(nil), "goshare.RspBatchDelete")
	proto.RegisterType((*ReqBatchGet)(nil), "goshare.ReqBatchGet")
	proto.RegisterType((*RspBatchGet)(nil), "goshare.RspBatchGet")
	proto.RegisterType((*ReqBatchPut)(nil), "goshare.ReqBatchPut")
	proto.RegisterType((*RspBatchPut)(nil), "goshare.RspBatchPut")
	proto.RegisterType((*ReqDelete)(nil), "goshare.ReqDelete")
	proto.RegisterType((*RspDelete)(nil), "goshare.RspDelete")
	proto.RegisterType((*ReqGet)(nil), "goshare.ReqGet")
	proto.RegisterType((*RspGet)(nil), "goshare.RspGet")
	proto.RegisterType((*ReqPut)(nil), "goshare.ReqPut")
	proto.RegisterType((*RspPut)(nil), "goshare.RspPut")
	proto.RegisterType((*ReqReverseScan)(nil), "goshare.ReqReverseScan")
	proto.RegisterType((*RspReverseScan)(nil), "goshare.RspReverseScan")
	proto.RegisterType((*ReqScan)(nil), "goshare.ReqScan")
	proto.RegisterType((*RspScan)(nil), "goshare.RspScan")
}

func init() { proto.RegisterFile("goshare/rpc.proto", fileDescriptor_49c3d35f07f60759) }

var fileDescriptor_49c3d35f07f60759 = []byte{
	// 1178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0xb7, 0xe3, 0xd8, 0x71, 0xd6, 0xa9, 0xeb, 0x5c, 0x9c, 0xd6, 0x55, 0x1a, 0x48, 0x6f, 0xf8,
	0xe3, 0x4e, 0xc1, 0xee, 0xb8, 0x3c, 0xc0, 0xf0, 0x00, 0x49, 0x4b, 0x1d, 0x28, 0x85, 0xcc, 0xb9,
	0xbc, 0xf0, 0x92, 0x91, 0xe5, 0x23, 0x16, 0xb6, 0x25, 0x59, 0x77, 0x0a, 0xf5, 0x13, 0x1f, 0x85,
	0xef, 0x03, 0x6f, 0x7c, 0x06, 0x3e, 0x08, 0x73, 0xab, 0x93, 0x75, 0x92, 0x93, 0x4c, 0x49, 0x3a,
	0x4c, 0xdf, 0x7c, 0xb7, 0xbb, 0xbf, 0xfd, 0xed, 0x9f, 0xdb, 0x95, 0x61, 0xfb, 0xcc, 0x17, 0x63,
	0x3b, 0xe4, 0xdd, 0x30, 0x70, 0x3a, 0x41, 0xe8, 0x4b, 0x9f, 0x6c, 0xe8, 0x2b, 0xab, 0x99, 0xc8,
	0x1c, 0x7f, 0x36, 0xf3, 0xbd, 0x58, 0x6c, 0xdd, 0x4b, 0x6e, 0x67, 0x76, 0x38, 0xe1, 0xf2, 0x74,
	0x64, 0x4b, 0x5b, 0x8b, 0x5a, 0x89, 0xc8, 0xf5, 0x84, 0x0c, 0xa3, 0x19, 0xf7, 0xa4, 0x96, 0x34,
	0x44, 0xe0, 0x8e, 0x78, 0xd8, 0x15, 0x82, 0xeb, 0x9b, 0x1d, 0x7d, 0xf3, 0x3a, 0xe2, 0x73, 0x37,
	0x8a, 0x2f, 0x69, 0x0f, 0x9a, 0x8c, 0xcf, 0xfb, 0x5c, 0x7e, 0xbb, 0x04, 0xf8, 0xde, 0x15, 0x92,
	0x58, 0x50, 0xe5, 0xaf, 0x9d, 0xb1, 0xed, 0x9d, 0xf1, 0x56, 0xf1, 0xa0, 0xd8, 0xde, 0x64, 0xcb,
	0x33, 0xfd, 0x0a, 0x9a, 0x4c, 0x04, 0xab, 0x36, 0x1f, 0xc3, 0xfa, 0xd4, 0x15, 0xb2, 0x55, 0x3c,
	0x28, 0xb5, 0x6b, 0xbd, 0x9d, 0x8e, 0xe6, 0xd6, 0x49, 0xd5, 0x18, 0x2a, 0xd0, 0x63, 0xd8, 0x66,
	0x7c, 0x3e, 0xb0, 0xcf, 0x79, 0x2a, 0x22, 0x4f, 0x00, 0xd2, 0x20, 0xd0, 0xe7, 0x25, 0x18, 0x86,
	0x1a, 0xdd, 0x81, 0x6d, 0x26, 0x82, 0x2c, 0x12, 0x7d, 0x0e, 0x8d, 0x7c, 0x4c, 0x57, 0xc5, 0x43,
	0xee, 0x40, 0x45, 0x2c, 0x66, 0x43, 0x7f, 0xda, 0x5a, 0x43, 0x89, 0x3e, 0xd1, 0x3e, 0x34, 0xf2,
	0x71, 0x5e, 0x8f, 0xe5, 0x6f, 0xb0, 0xa5, 0xe2, 0x8d, 0x86, 0xc2, 0x09, 0xdd, 0x21, 0xbf, 0x0e,
	0x19, 0x42, 0x74, 0x72, 0x4b, 0x07, 0xa5, 0xf6, 0x66, 0x9c, 0x47, 0xf2, 0x3e, 0xd4, 0x86, 0xae,
	0x67, 0x87, 0x0b, 0x6c, 0x89, 0xd6, 0xfa, 0x41, 0xb1, 0x5d, 0x65, 0x10, 0x5f, 0x3d, 0xb3, 0xa5,
	0x4d, 0xeb, 0xb0, 0xa5, 0xd2, 0x93, 0x38, 0xa6, 0x5f, 0x43, 0x9d, 0xf1, 0xf9, 0x4f, 0xde, 0x9b,
	0x51, 0x49, 0x5c, 0xae, 0xa5, 0x2e, 0x69, 0x03, 0xea, 0x4c, 0x04, 0x06, 0x02, 0xfd, 0x1d, 0x76,
	0x18, 0x9f, 0x3f, 0xf5, 0x67, 0x43, 0xd7, 0xe3, 0x37, 0x8b, 0xf1, 0x33, 0xa8, 0x05, 0x3c, 0x74,
	0xfd, 0xd1, 0xe9, 0x32, 0xd4, 0xba, 0x91, 0xdd, 0x13, 0x94, 0xbd, 0x5a, 0x04, 0x9c, 0x41, 0xac,
	0xa7, 0xda, 0x8e, 0xfe, 0x5d, 0x84, 0x1d, 0x26, 0x82, 0xb7, 0xc2, 0xa0, 0x03, 0x1b, 0x63, 0x57,
	0x48, 0x3f, 0x5c, 0xa0, 0xf7, 0x5a, 0xaf, 0xb9, 0xf4, 0xfe, 0x62, 0xaa, 0xd0, 0x79, 0xe8, 0x72,
	0xc1, 0x12, 0x25, 0xd2, 0x85, 0x75, 0xe9, 0x3a, 0x13, 0x4c, 0x7d, 0xad, 0xb7, 0xb7, 0x54, 0x7e,
	0x89, 0x2f, 0x55, 0xd5, 0x60, 0xe0, 0xd9, 0x81, 0x18, 0xfb, 0x92, 0xa1, 0x22, 0xf9, 0x08, 0x2a,
	0x13, 0x05, 0x24, 0x5a, 0x65, 0xc4, 0xaf, 0x67, 0xf1, 0x99, 0x96, 0x52, 0x2f, 0xe9, 0xe1, 0x57,
	0xae, 0x33, 0x89, 0xbd, 0x5e, 0x2b, 0xa0, 0x26, 0x94, 0x85, 0xb4, 0x43, 0x95, 0xcc, 0x62, 0xbb,
	0xcc, 0xe2, 0x03, 0x69, 0x40, 0x89, 0x7b, 0x23, 0x64, 0x5d, 0x66, 0xea, 0x27, 0xfd, 0xa3, 0x98,
	0x34, 0xfb, 0xff, 0xe3, 0x50, 0x65, 0x0e, 0x8b, 0x1c, 0xa7, 0xe1, 0xea, 0xcc, 0x61, 0xe7, 0xfd,
	0x55, 0x04, 0xa2, 0xa7, 0x86, 0x51, 0x8a, 0x6b, 0x71, 0x7c, 0x04, 0x95, 0xb8, 0x7f, 0x90, 0xe4,
	0x25, 0x2d, 0xa6, 0x55, 0xc8, 0x63, 0xa8, 0xd8, 0xa3, 0x5f, 0x23, 0x21, 0x91, 0x7d, 0xbd, 0xd7,
	0x4a, 0x95, 0x43, 0xd7, 0xe1, 0x87, 0x28, 0x8b, 0x2d, 0x62, 0x3d, 0x42, 0x33, 0xa1, 0xe5, 0x2b,
	0x1c, 0x47, 0xd3, 0x04, 0xa2, 0x07, 0x97, 0x11, 0x8c, 0x6a, 0xe5, 0xed, 0xb8, 0xec, 0xef, 0x78,
	0x88, 0xcb, 0x2a, 0x97, 0x0f, 0x8a, 0xed, 0x52, 0x52, 0xe5, 0x26, 0x94, 0x1d, 0x3f, 0xf2, 0x64,
	0xab, 0x12, 0xd7, 0x1e, 0x0f, 0xf4, 0xcf, 0x22, 0x0e, 0xe9, 0x77, 0x3f, 0xa8, 0x37, 0xa9, 0xdb,
	0x5d, 0xd8, 0x55, 0x4d, 0x38, 0xf8, 0x66, 0x20, 0x7d, 0x67, 0xf2, 0x63, 0x20, 0x5d, 0xdf, 0xc3,
	0x29, 0xf4, 0x02, 0x76, 0x55, 0x41, 0x57, 0x04, 0xa4, 0x97, 0xd9, 0x8a, 0xef, 0x2d, 0x51, 0xe3,
	0x6d, 0xdc, 0xc9, 0x5a, 0x68, 0x2f, 0x12, 0x67, 0xaa, 0xea, 0x8e, 0x23, 0xdf, 0x8b, 0xc4, 0xb1,
	0x9e, 0x36, 0xd7, 0xc9, 0xd9, 0x43, 0x63, 0x6f, 0xd4, 0x7a, 0xbb, 0x79, 0xf7, 0x88, 0xaf, 0xbd,
	0xee, 0xe2, 0x1c, 0xcd, 0x7b, 0xa5, 0xc7, 0xf8, 0xee, 0xfa, 0x5c, 0xde, 0x94, 0x0b, 0x15, 0xd8,
	0xf4, 0x6f, 0x01, 0xe9, 0xbf, 0x44, 0xf5, 0x01, 0xee, 0xbc, 0x23, 0x5b, 0x3a, 0xe3, 0x67, 0x7c,
	0xca, 0x25, 0xee, 0xb5, 0x09, 0x5f, 0x08, 0xac, 0xc8, 0x16, 0xc3, 0xdf, 0x7a, 0xaf, 0x19, 0x5a,
	0xf4, 0x01, 0xd4, 0x12, 0xbb, 0x3e, 0x97, 0x17, 0x1a, 0x7d, 0x08, 0xb5, 0xc4, 0x48, 0xa9, 0xdc,
	0x81, 0xca, 0xb9, 0x3d, 0x8d, 0x78, 0xa2, 0xa4, 0x4f, 0xf4, 0x8b, 0x14, 0xe9, 0x24, 0xba, 0x10,
	0xc9, 0x30, 0x5d, 0xcb, 0x98, 0xde, 0x4a, 0x3d, 0x9c, 0x44, 0x92, 0xee, 0xc3, 0x26, 0xe3, 0x73,
	0x1d, 0x46, 0x03, 0x4a, 0x13, 0xbe, 0xc0, 0x94, 0x6d, 0x31, 0xf5, 0x93, 0xd6, 0x60, 0x93, 0x89,
	0x40, 0xf3, 0xb7, 0xa0, 0x12, 0x97, 0xed, 0x02, 0xc5, 0x2f, 0xa1, 0x12, 0x17, 0x42, 0x3d, 0x59,
	0x74, 0xa5, 0xa5, 0xf1, 0x81, 0xec, 0xc1, 0xa6, 0xe7, 0xcb, 0xd3, 0x5f, 0xfc, 0xc8, 0x1b, 0x61,
	0xe6, 0xab, 0xac, 0xea, 0xf9, 0xf2, 0xb9, 0x3a, 0xd3, 0xc7, 0x08, 0xac, 0x22, 0x59, 0x01, 0x4e,
	0xe1, 0xd6, 0x0c, 0x38, 0x5a, 0x45, 0x77, 0x2a, 0x80, 0x1f, 0xb0, 0x18, 0x8c, 0x9f, 0xf3, 0x50,
	0xf0, 0x81, 0x63, 0x7b, 0xe9, 0x24, 0xd1, 0x04, 0x32, 0xfb, 0x22, 0x46, 0xc1, 0x7d, 0xd1, 0x84,
	0xf2, 0xd4, 0x9d, 0xb9, 0xcb, 0xbd, 0x82, 0x07, 0xda, 0xc6, 0xb2, 0x99, 0x78, 0x97, 0x15, 0xa1,
	0x0f, 0x1b, 0xea, 0x49, 0xdd, 0xdc, 0xe5, 0x03, 0xd8, 0x50, 0xaf, 0xe4, 0x0a, 0x5f, 0xbd, 0x7f,
	0x36, 0x00, 0x70, 0x68, 0x3c, 0xb5, 0x9d, 0x31, 0x27, 0x2f, 0xe1, 0x76, 0x7e, 0x6b, 0xa5, 0xfb,
	0x6e, 0x75, 0xa5, 0x59, 0x86, 0x70, 0x75, 0x45, 0x14, 0xc8, 0x77, 0x50, 0xcf, 0xcf, 0x52, 0x13,
	0x2d, 0x2b, 0xb3, 0x2c, 0x13, 0x2c, 0x2b, 0x8b, 0xb1, 0x72, 0x9f, 0xe1, 0x56, 0x9e, 0x59, 0x2a,
	0xcb, 0x62, 0xe5, 0x3e, 0xba, 0x0b, 0xa4, 0x0f, 0xb7, 0xb2, 0xdf, 0xca, 0xf7, 0x72, 0xb4, 0x0c,
	0xa4, 0x7b, 0x39, 0x56, 0x19, 0xa0, 0x01, 0x6c, 0xaf, 0xfe, 0xb9, 0xd8, 0xbf, 0x14, 0x4c, 0x89,
	0xad, 0xfd, 0x4b, 0x01, 0x71, 0x3a, 0x17, 0xc8, 0x09, 0x34, 0x56, 0xe6, 0xe9, 0xfd, 0x7c, 0xac,
	0xa6, 0xd4, 0xba, 0x9f, 0x8f, 0x36, 0x33, 0x15, 0x0b, 0xaa, 0xac, 0xf9, 0x51, 0xb6, 0x97, 0x23,
	0x99, 0xc1, 0xdb, 0xcb, 0x51, 0xcc, 0xc1, 0x1d, 0x42, 0xcd, 0x1c, 0x52, 0x77, 0x4d, 0x28, 0x43,
	0x60, 0xdd, 0x35, 0x61, 0xcc, 0x81, 0x55, 0x20, 0x9f, 0x43, 0x75, 0x39, 0x8c, 0x9a, 0x2b, 0xf6,
	0x7d, 0x2e, 0xad, 0xe6, 0x8a, 0x71, 0x9f, 0x4b, 0xc3, 0x52, 0xbd, 0xea, 0x55, 0xcb, 0x93, 0xe8,
	0x22, 0x4b, 0xf5, 0x9e, 0x0b, 0xa4, 0x07, 0x95, 0x64, 0xac, 0x9a, 0x76, 0x9a, 0x2c, 0x31, 0xad,
	0x96, 0x3c, 0x1f, 0x42, 0x49, 0x51, 0xbc, 0x9d, 0xcb, 0x96, 0x75, 0x3b, 0x97, 0xa1, 0x58, 0x55,
	0x71, 0xca, 0xa8, 0x2a, 0x3a, 0x19, 0xd5, 0x98, 0xc9, 0xa1, 0x1a, 0xb3, 0xe9, 0x20, 0xc8, 0x24,
	0xd0, 0x10, 0x64, 0x13, 0x68, 0x08, 0x68, 0x81, 0x7c, 0x02, 0xeb, 0x68, 0xdb, 0xc8, 0x34, 0x86,
	0x32, 0x6a, 0x64, 0x9a, 0x01, 0xb5, 0x8f, 0x3e, 0xfd, 0xf9, 0xd1, 0x99, 0x2b, 0xc7, 0xd1, 0xb0,
	0xe3, 0xf8, 0xb3, 0xee, 0xcc, 0xf5, 0x78, 0x68, 0x4f, 0x43, 0x2e, 0xba, 0xf8, 0xd7, 0x5a, 0x74,
	0x45, 0xe8, 0x74, 0xcf, 0xfc, 0xae, 0x36, 0x1c, 0x56, 0xf0, 0xfa, 0xc9, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x6b, 0x8a, 0x66, 0xdb, 0x01, 0x10, 0x00, 0x00,
}
