// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goshare/strategy.proto

package goshare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Signal 交易信号
type Signal struct {
	OpenTime               int64    `protobuf:"varint,1,opt,name=open_time,json=openTime,proto3" json:"openTime"`
	OpenPrice              float64  `protobuf:"fixed64,2,opt,name=open_price,json=openPrice,proto3" json:"openPrice"`
	CloseTime              int64    `protobuf:"varint,3,opt,name=close_time,json=closeTime,proto3" json:"closeTime"`
	ClosePrice             float64  `protobuf:"fixed64,4,opt,name=close_price,json=closePrice,proto3" json:"closePrice"`
	Volume                 int32    `protobuf:"varint,5,opt,name=volume,proto3" json:"volume"`
	Direction              int32    `protobuf:"varint,6,opt,name=direction,proto3" json:"direction"`
	Profit                 float64  `protobuf:"fixed64,7,opt,name=profit,proto3" json:"profit"`
	AccumulativeProfit     float64  `protobuf:"fixed64,8,opt,name=accumulative_profit,json=accumulativeProfit,proto3" json:"accumulativeProfit"`
	Commission             float64  `protobuf:"fixed64,9,opt,name=commission,proto3" json:"commission"`
	AccumulativeCommission float64  `protobuf:"fixed64,10,opt,name=accumulative_commission,json=accumulativeCommission,proto3" json:"accumulativeCommission"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *Signal) Reset()         { *m = Signal{} }
func (m *Signal) String() string { return proto.CompactTextString(m) }
func (*Signal) ProtoMessage()    {}
func (*Signal) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff86ba7f940749c6, []int{0}
}

func (m *Signal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Signal.Unmarshal(m, b)
}
func (m *Signal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Signal.Marshal(b, m, deterministic)
}
func (m *Signal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Signal.Merge(m, src)
}
func (m *Signal) XXX_Size() int {
	return xxx_messageInfo_Signal.Size(m)
}
func (m *Signal) XXX_DiscardUnknown() {
	xxx_messageInfo_Signal.DiscardUnknown(m)
}

var xxx_messageInfo_Signal proto.InternalMessageInfo

func (m *Signal) GetOpenTime() int64 {
	if m != nil {
		return m.OpenTime
	}
	return 0
}

func (m *Signal) GetOpenPrice() float64 {
	if m != nil {
		return m.OpenPrice
	}
	return 0
}

func (m *Signal) GetCloseTime() int64 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

func (m *Signal) GetClosePrice() float64 {
	if m != nil {
		return m.ClosePrice
	}
	return 0
}

func (m *Signal) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *Signal) GetDirection() int32 {
	if m != nil {
		return m.Direction
	}
	return 0
}

func (m *Signal) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *Signal) GetAccumulativeProfit() float64 {
	if m != nil {
		return m.AccumulativeProfit
	}
	return 0
}

func (m *Signal) GetCommission() float64 {
	if m != nil {
		return m.Commission
	}
	return 0
}

func (m *Signal) GetAccumulativeCommission() float64 {
	if m != nil {
		return m.AccumulativeCommission
	}
	return 0
}

// strategy signal
type AnalyzeResult struct {
	Profit               float64  `protobuf:"fixed64,1,opt,name=profit,proto3" json:"profit"`
	MaxDrawdown          float64  `protobuf:"fixed64,2,opt,name=max_drawdown,json=maxDrawdown,proto3" json:"maxDrawdown"`
	TakeTimes            int32    `protobuf:"varint,3,opt,name=take_times,json=takeTimes,proto3" json:"takeTimes"`
	LossTimes            int32    `protobuf:"varint,4,opt,name=loss_times,json=lossTimes,proto3" json:"lossTimes"`
	TradeTimes           int32    `protobuf:"varint,5,opt,name=trade_times,json=tradeTimes,proto3" json:"tradeTimes"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AnalyzeResult) Reset()         { *m = AnalyzeResult{} }
func (m *AnalyzeResult) String() string { return proto.CompactTextString(m) }
func (*AnalyzeResult) ProtoMessage()    {}
func (*AnalyzeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff86ba7f940749c6, []int{1}
}

func (m *AnalyzeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AnalyzeResult.Unmarshal(m, b)
}
func (m *AnalyzeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AnalyzeResult.Marshal(b, m, deterministic)
}
func (m *AnalyzeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AnalyzeResult.Merge(m, src)
}
func (m *AnalyzeResult) XXX_Size() int {
	return xxx_messageInfo_AnalyzeResult.Size(m)
}
func (m *AnalyzeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AnalyzeResult.DiscardUnknown(m)
}

var xxx_messageInfo_AnalyzeResult proto.InternalMessageInfo

func (m *AnalyzeResult) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *AnalyzeResult) GetMaxDrawdown() float64 {
	if m != nil {
		return m.MaxDrawdown
	}
	return 0
}

func (m *AnalyzeResult) GetTakeTimes() int32 {
	if m != nil {
		return m.TakeTimes
	}
	return 0
}

func (m *AnalyzeResult) GetLossTimes() int32 {
	if m != nil {
		return m.LossTimes
	}
	return 0
}

func (m *AnalyzeResult) GetTradeTimes() int32 {
	if m != nil {
		return m.TradeTimes
	}
	return 0
}

// SignalList list
type SignalList struct {
	Exchange             string         `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange"`
	Symbol               string         `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol"`
	Multiple             float64        `protobuf:"fixed64,3,opt,name=multiple,proto3" json:"multiple"`
	PriceTick            float64        `protobuf:"fixed64,4,opt,name=price_tick,json=priceTick,proto3" json:"priceTick"`
	List                 []*Signal      `protobuf:"bytes,5,rep,name=list,proto3" json:"list"`
	Result               *AnalyzeResult `protobuf:"bytes,6,opt,name=result,proto3" json:"result"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SignalList) Reset()         { *m = SignalList{} }
func (m *SignalList) String() string { return proto.CompactTextString(m) }
func (*SignalList) ProtoMessage()    {}
func (*SignalList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ff86ba7f940749c6, []int{2}
}

func (m *SignalList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignalList.Unmarshal(m, b)
}
func (m *SignalList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignalList.Marshal(b, m, deterministic)
}
func (m *SignalList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignalList.Merge(m, src)
}
func (m *SignalList) XXX_Size() int {
	return xxx_messageInfo_SignalList.Size(m)
}
func (m *SignalList) XXX_DiscardUnknown() {
	xxx_messageInfo_SignalList.DiscardUnknown(m)
}

var xxx_messageInfo_SignalList proto.InternalMessageInfo

func (m *SignalList) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *SignalList) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *SignalList) GetMultiple() float64 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

func (m *SignalList) GetPriceTick() float64 {
	if m != nil {
		return m.PriceTick
	}
	return 0
}

func (m *SignalList) GetList() []*Signal {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *SignalList) GetResult() *AnalyzeResult {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*Signal)(nil), "goshare.Signal")
	proto.RegisterType((*AnalyzeResult)(nil), "goshare.AnalyzeResult")
	proto.RegisterType((*SignalList)(nil), "goshare.SignalList")
}

func init() { proto.RegisterFile("goshare/strategy.proto", fileDescriptor_ff86ba7f940749c6) }

var fileDescriptor_ff86ba7f940749c6 = []byte{
	// 462 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x53, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x55, 0xa6, 0x8f, 0x69, 0x6e, 0x40, 0x48, 0x46, 0x2a, 0x11, 0xaf, 0x29, 0x65, 0x53, 0x09,
	0x91, 0x48, 0xc3, 0x82, 0x35, 0x8f, 0x25, 0x8b, 0x91, 0x99, 0x15, 0x9b, 0xca, 0x75, 0x4d, 0x6a,
	0xd5, 0x8e, 0x23, 0xdb, 0x99, 0x69, 0xf9, 0x23, 0xfe, 0x86, 0x0f, 0xe0, 0x63, 0x90, 0xaf, 0x4d,
	0xa6, 0x5d, 0xde, 0xf3, 0xb8, 0xbe, 0x3d, 0x3d, 0x81, 0x79, 0x63, 0xdc, 0x8e, 0x59, 0x51, 0x3b,
	0x6f, 0x99, 0x17, 0xcd, 0xb1, 0xea, 0xac, 0xf1, 0x86, 0x5c, 0x26, 0x7c, 0xf9, 0xf7, 0x02, 0xa6,
	0xdf, 0x65, 0xd3, 0x32, 0x45, 0x5e, 0x40, 0x6e, 0x3a, 0xd1, 0xae, 0xbd, 0xd4, 0xa2, 0xcc, 0x16,
	0xd9, 0x6a, 0x44, 0x67, 0x01, 0xb8, 0x95, 0x5a, 0x90, 0x57, 0x00, 0x48, 0x76, 0x56, 0x72, 0x51,
	0x5e, 0x2c, 0xb2, 0x55, 0x46, 0x51, 0x7e, 0x13, 0x80, 0x40, 0x73, 0x65, 0x9c, 0x88, 0xe6, 0x11,
	0x9a, 0x73, 0x44, 0xd0, 0x7d, 0x05, 0x45, 0xa4, 0xa3, 0x7d, 0x8c, 0xf6, 0xe8, 0x88, 0xfe, 0x39,
	0x4c, 0xef, 0x8c, 0xea, 0xb5, 0x28, 0x27, 0x8b, 0x6c, 0x35, 0xa1, 0x69, 0x22, 0x2f, 0x21, 0xdf,
	0x4a, 0x2b, 0xb8, 0x97, 0xa6, 0x2d, 0xa7, 0x48, 0x3d, 0x00, 0xc1, 0xd5, 0x59, 0xf3, 0x53, 0xfa,
	0xf2, 0x12, 0x37, 0xa6, 0x89, 0xd4, 0xf0, 0x94, 0x71, 0xde, 0xeb, 0x5e, 0x31, 0x2f, 0xef, 0xc2,
	0xab, 0x28, 0x9a, 0xa1, 0x88, 0x9c, 0x52, 0x37, 0xd1, 0xf0, 0x1a, 0x80, 0x1b, 0xad, 0xa5, 0x73,
	0xe1, 0x9d, 0x3c, 0x9d, 0x37, 0x20, 0xe4, 0x23, 0x3c, 0x3b, 0x5b, 0x78, 0x22, 0x06, 0x14, 0xcf,
	0x4f, 0xe9, 0x2f, 0x03, 0xbb, 0xfc, 0x9d, 0xc1, 0xe3, 0x4f, 0x2d, 0x53, 0xc7, 0x5f, 0x82, 0x0a,
	0xd7, 0x2b, 0x7f, 0x72, 0x73, 0x76, 0x76, 0xf3, 0x1b, 0x78, 0xa4, 0xd9, 0x61, 0xbd, 0xb5, 0xec,
	0x7e, 0x6b, 0xee, 0xdb, 0x14, 0x71, 0xa1, 0xd9, 0xe1, 0x6b, 0x82, 0x42, 0xc8, 0x9e, 0xed, 0x63,
	0xc6, 0x0e, 0x43, 0x9e, 0xd0, 0x3c, 0x20, 0x21, 0x63, 0x17, 0x68, 0x65, 0x9c, 0x4b, 0xf4, 0x38,
	0xd2, 0x01, 0x89, 0xf4, 0x15, 0x14, 0xde, 0xb2, 0xed, 0x7f, 0x7b, 0xcc, 0x19, 0x10, 0x42, 0xc1,
	0xf2, 0x4f, 0x06, 0x10, 0xab, 0xf0, 0x4d, 0x3a, 0x4f, 0x9e, 0xc3, 0x4c, 0x1c, 0xf8, 0x8e, 0xb5,
	0x4d, 0x6c, 0x43, 0x4e, 0x87, 0x39, 0xfc, 0x08, 0x77, 0xd4, 0x1b, 0xa3, 0xf0, 0xcc, 0x9c, 0xa6,
	0x29, 0x78, 0x74, 0xaf, 0xbc, 0xec, 0x54, 0x2c, 0x41, 0x46, 0x87, 0x39, 0x9c, 0x87, 0xff, 0xfe,
	0xda, 0x4b, 0xbe, 0x4f, 0x15, 0xc8, 0x11, 0xb9, 0x95, 0x7c, 0x4f, 0xde, 0xc2, 0x58, 0x49, 0xe7,
	0xcb, 0xc9, 0x62, 0xb4, 0x2a, 0xae, 0x9f, 0x54, 0xa9, 0xa0, 0x55, 0xbc, 0x88, 0x22, 0x49, 0x2a,
	0x98, 0x5a, 0x8c, 0x11, 0xbb, 0x50, 0x5c, 0xcf, 0x07, 0xd9, 0x59, 0xc8, 0x34, 0xa9, 0x3e, 0xbf,
	0xff, 0xf1, 0xae, 0x91, 0x7e, 0xd7, 0x6f, 0x2a, 0x6e, 0x74, 0xad, 0x65, 0x2b, 0x2c, 0x53, 0x56,
	0xb8, 0x1a, 0xbf, 0x02, 0x57, 0x3b, 0xcb, 0xeb, 0xc6, 0xd4, 0x69, 0xc9, 0x66, 0x8a, 0xf0, 0x87,
	0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x82, 0x0c, 0xd7, 0x36, 0x03, 0x00, 0x00,
}
