// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goshare/user.proto

package goshare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// enum 用户类型
type UserType int32

const (
	UserType_UT_NORMAL       UserType = 0
	UserType_UT_BRANCH_ADMIN UserType = 1
	UserType_UT_SYSTEM_ADMIN UserType = 2
)

var UserType_name = map[int32]string{
	0: "UT_NORMAL",
	1: "UT_BRANCH_ADMIN",
	2: "UT_SYSTEM_ADMIN",
}

var UserType_value = map[string]int32{
	"UT_NORMAL":       0,
	"UT_BRANCH_ADMIN": 1,
	"UT_SYSTEM_ADMIN": 2,
}

func (x UserType) String() string {
	return proto.EnumName(UserType_name, int32(x))
}

func (UserType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{0}
}

// UserStatus 状态
type UserStatus int32

const (
	UserStatus_US_NORMAL  UserStatus = 0
	UserStatus_US_FROZEN  UserStatus = 1
	UserStatus_US_DELETED UserStatus = 2
)

var UserStatus_name = map[int32]string{
	0: "US_NORMAL",
	1: "US_FROZEN",
	2: "US_DELETED",
}

var UserStatus_value = map[string]int32{
	"US_NORMAL":  0,
	"US_FROZEN":  1,
	"US_DELETED": 2,
}

func (x UserStatus) String() string {
	return proto.EnumName(UserStatus_name, int32(x))
}

func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{1}
}

// 用户
type User struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Type                 UserType   `protobuf:"varint,3,opt,name=type,proto3,enum=goshare.UserType" json:"type"`
	Status               UserStatus `protobuf:"varint,4,opt,name=status,proto3,enum=goshare.UserStatus" json:"status"`
	Roles                []int64    `protobuf:"varint,5,rep,packed,name=roles,proto3" json:"roles"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetType() UserType {
	if m != nil {
		return m.Type
	}
	return UserType_UT_NORMAL
}

func (m *User) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_US_NORMAL
}

func (m *User) GetRoles() []int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

type UserList struct {
	List                 []*User  `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserList) Reset()         { *m = UserList{} }
func (m *UserList) String() string { return proto.CompactTextString(m) }
func (*UserList) ProtoMessage()    {}
func (*UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{1}
}

func (m *UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserList.Unmarshal(m, b)
}
func (m *UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserList.Marshal(b, m, deterministic)
}
func (m *UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserList.Merge(m, src)
}
func (m *UserList) XXX_Size() int {
	return xxx_messageInfo_UserList.Size(m)
}
func (m *UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_UserList proto.InternalMessageInfo

func (m *UserList) GetList() []*User {
	if m != nil {
		return m.List
	}
	return nil
}

// Permission 权限
type Permission struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Menus                []string `protobuf:"bytes,3,rep,name=menus,proto3" json:"menus"`
	Apis                 []string `protobuf:"bytes,4,rep,name=apis,proto3" json:"apis"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{2}
}

func (m *Permission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Permission.Unmarshal(m, b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return xxx_messageInfo_Permission.Size(m)
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Permission) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Permission) GetMenus() []string {
	if m != nil {
		return m.Menus
	}
	return nil
}

func (m *Permission) GetApis() []string {
	if m != nil {
		return m.Apis
	}
	return nil
}

// PermissionTreeNode 权限树节点
type PermissionTreeNode struct {
	Permission           *Permission           `protobuf:"bytes,1,opt,name=permission,proto3" json:"permission"`
	Selected             bool                  `protobuf:"varint,2,opt,name=selected,proto3" json:"selected"`
	Children             []*PermissionTreeNode `protobuf:"bytes,3,rep,name=children,proto3" json:"children"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PermissionTreeNode) Reset()         { *m = PermissionTreeNode{} }
func (m *PermissionTreeNode) String() string { return proto.CompactTextString(m) }
func (*PermissionTreeNode) ProtoMessage()    {}
func (*PermissionTreeNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{3}
}

func (m *PermissionTreeNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionTreeNode.Unmarshal(m, b)
}
func (m *PermissionTreeNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionTreeNode.Marshal(b, m, deterministic)
}
func (m *PermissionTreeNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionTreeNode.Merge(m, src)
}
func (m *PermissionTreeNode) XXX_Size() int {
	return xxx_messageInfo_PermissionTreeNode.Size(m)
}
func (m *PermissionTreeNode) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionTreeNode.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionTreeNode proto.InternalMessageInfo

func (m *PermissionTreeNode) GetPermission() *Permission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *PermissionTreeNode) GetSelected() bool {
	if m != nil {
		return m.Selected
	}
	return false
}

func (m *PermissionTreeNode) GetChildren() []*PermissionTreeNode {
	if m != nil {
		return m.Children
	}
	return nil
}

// PermissionList 权限列表
type PermissionList struct {
	List                 []*Permission `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PermissionList) Reset()         { *m = PermissionList{} }
func (m *PermissionList) String() string { return proto.CompactTextString(m) }
func (*PermissionList) ProtoMessage()    {}
func (*PermissionList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{4}
}

func (m *PermissionList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionList.Unmarshal(m, b)
}
func (m *PermissionList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionList.Marshal(b, m, deterministic)
}
func (m *PermissionList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionList.Merge(m, src)
}
func (m *PermissionList) XXX_Size() int {
	return xxx_messageInfo_PermissionList.Size(m)
}
func (m *PermissionList) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionList.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionList proto.InternalMessageInfo

func (m *PermissionList) GetList() []*Permission {
	if m != nil {
		return m.List
	}
	return nil
}

// 角色
type UserRole struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Name                 string        `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Discription          string        `protobuf:"bytes,3,opt,name=discription,proto3" json:"discription"`
	Permissions          []*Permission `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UserRole) Reset()         { *m = UserRole{} }
func (m *UserRole) String() string { return proto.CompactTextString(m) }
func (*UserRole) ProtoMessage()    {}
func (*UserRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{5}
}

func (m *UserRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRole.Unmarshal(m, b)
}
func (m *UserRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRole.Marshal(b, m, deterministic)
}
func (m *UserRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRole.Merge(m, src)
}
func (m *UserRole) XXX_Size() int {
	return xxx_messageInfo_UserRole.Size(m)
}
func (m *UserRole) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRole.DiscardUnknown(m)
}

var xxx_messageInfo_UserRole proto.InternalMessageInfo

func (m *UserRole) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserRole) GetDiscription() string {
	if m != nil {
		return m.Discription
	}
	return ""
}

func (m *UserRole) GetPermissions() []*Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

// 用户会话
type Session struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id"`
	Token                string     `protobuf:"bytes,2,opt,name=token,proto3" json:"token"`
	Type                 UserType   `protobuf:"varint,3,opt,name=type,proto3,enum=goshare.UserType" json:"type"`
	Status               UserStatus `protobuf:"varint,4,opt,name=status,proto3,enum=goshare.UserStatus" json:"status"`
	Roles                []int64    `protobuf:"varint,5,rep,packed,name=roles,proto3" json:"roles"`
	Deadline             int64      `protobuf:"varint,6,opt,name=deadline,proto3" json:"deadline"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_d95acd2a4cac0d87, []int{6}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Session) GetType() UserType {
	if m != nil {
		return m.Type
	}
	return UserType_UT_NORMAL
}

func (m *Session) GetStatus() UserStatus {
	if m != nil {
		return m.Status
	}
	return UserStatus_US_NORMAL
}

func (m *Session) GetRoles() []int64 {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *Session) GetDeadline() int64 {
	if m != nil {
		return m.Deadline
	}
	return 0
}

func init() {
	proto.RegisterEnum("goshare.UserType", UserType_name, UserType_value)
	proto.RegisterEnum("goshare.UserStatus", UserStatus_name, UserStatus_value)
	proto.RegisterType((*User)(nil), "goshare.User")
	proto.RegisterType((*UserList)(nil), "goshare.UserList")
	proto.RegisterType((*Permission)(nil), "goshare.Permission")
	proto.RegisterType((*PermissionTreeNode)(nil), "goshare.PermissionTreeNode")
	proto.RegisterType((*PermissionList)(nil), "goshare.PermissionList")
	proto.RegisterType((*UserRole)(nil), "goshare.UserRole")
	proto.RegisterType((*Session)(nil), "goshare.Session")
}

func init() { proto.RegisterFile("goshare/user.proto", fileDescriptor_d95acd2a4cac0d87) }

var fileDescriptor_d95acd2a4cac0d87 = []byte{
	// 507 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0xc1, 0x6e, 0xda, 0x40,
	0x10, 0xad, 0x31, 0x10, 0x18, 0x14, 0x4a, 0x37, 0x1c, 0xac, 0xf6, 0xe2, 0x5a, 0xaa, 0x8a, 0x12,
	0x05, 0x4b, 0x44, 0x55, 0xd5, 0xde, 0x48, 0xa0, 0x6a, 0x25, 0x20, 0xd5, 0xda, 0x1c, 0xca, 0x05,
	0x39, 0x78, 0x04, 0xab, 0xda, 0x5e, 0x6b, 0x77, 0x39, 0xe4, 0x0b, 0xfa, 0x03, 0x3d, 0xf7, 0x2f,
	0xfa, 0x7f, 0x95, 0xd7, 0x2e, 0x36, 0x55, 0x22, 0xf5, 0x94, 0xdb, 0xce, 0x9b, 0xe7, 0x37, 0x6f,
	0xde, 0xae, 0x81, 0x6c, 0xb9, 0xdc, 0x05, 0x02, 0xdd, 0xbd, 0x44, 0x31, 0x4c, 0x05, 0x57, 0x9c,
	0x9c, 0x14, 0x98, 0xf3, 0xd3, 0x80, 0xfa, 0x52, 0xa2, 0x20, 0x5d, 0xa8, 0xb1, 0xd0, 0x32, 0x6c,
	0x63, 0xd0, 0xa6, 0x35, 0x16, 0x12, 0x02, 0xf5, 0x24, 0x88, 0xd1, 0xaa, 0x69, 0x44, 0x9f, 0xc9,
	0x1b, 0xa8, 0xab, 0xfb, 0x14, 0x2d, 0xd3, 0x36, 0x06, 0xdd, 0xd1, 0x8b, 0x61, 0x21, 0x32, 0xcc,
	0x04, 0xfc, 0xfb, 0x14, 0xa9, 0x6e, 0x93, 0x0b, 0x68, 0x4a, 0x15, 0xa8, 0xbd, 0xb4, 0xea, 0x9a,
	0x78, 0x76, 0x44, 0xf4, 0x74, 0x8b, 0x16, 0x14, 0xd2, 0x87, 0x86, 0xe0, 0x11, 0x4a, 0xab, 0x61,
	0x9b, 0x03, 0x93, 0xe6, 0x85, 0x73, 0x09, 0xad, 0x8c, 0x3b, 0x63, 0x52, 0x91, 0xd7, 0x50, 0x8f,
	0x98, 0x54, 0x96, 0x61, 0x9b, 0x83, 0xce, 0xe8, 0xf4, 0x48, 0x8c, 0xea, 0x96, 0xb3, 0x02, 0xf8,
	0x8a, 0x22, 0x66, 0x52, 0x32, 0x9e, 0x54, 0x56, 0x31, 0x1f, 0x5d, 0xa5, 0x0f, 0x8d, 0x18, 0x93,
	0xbd, 0xb4, 0x4c, 0xdb, 0x1c, 0xb4, 0x69, 0x5e, 0x64, 0xcc, 0x20, 0x65, 0x99, 0xef, 0x0c, 0xd4,
	0x67, 0xe7, 0x97, 0x01, 0xa4, 0x14, 0xf7, 0x05, 0xe2, 0x82, 0x87, 0x48, 0xae, 0x00, 0xd2, 0x03,
	0xaa, 0x87, 0x75, 0x2a, 0x8b, 0x96, 0x1f, 0xd0, 0x0a, 0x8d, 0xbc, 0x84, 0x96, 0xc4, 0x08, 0x37,
	0x0a, 0x43, 0xed, 0xa6, 0x45, 0x0f, 0x35, 0x79, 0x0f, 0xad, 0xcd, 0x8e, 0x45, 0xa1, 0xc0, 0x44,
	0x9b, 0xea, 0x8c, 0x5e, 0x3d, 0x20, 0xf7, 0x77, 0x3e, 0x3d, 0x90, 0x9d, 0x0f, 0xd0, 0x2d, 0xfb,
	0x3a, 0xb1, 0xb7, 0x47, 0x89, 0x3d, 0xe8, 0x2a, 0xcf, 0xed, 0x87, 0x91, 0xe7, 0x4c, 0x79, 0x84,
	0xff, 0x15, 0x9b, 0x0d, 0x9d, 0x90, 0xc9, 0x8d, 0x60, 0xa9, 0xca, 0xd6, 0x36, 0x75, 0xab, 0x0a,
	0x91, 0x77, 0xd0, 0x29, 0x17, 0xce, 0x93, 0x7c, 0xc4, 0x42, 0x95, 0xe7, 0xfc, 0x36, 0xe0, 0xc4,
	0xc3, 0x7f, 0xef, 0x2f, 0x7f, 0x8a, 0x7d, 0x68, 0x28, 0xfe, 0x1d, 0x93, 0xc2, 0x49, 0x5e, 0x3c,
	0xdd, 0x63, 0xcc, 0x6e, 0x2d, 0xc4, 0x20, 0x8c, 0x58, 0x82, 0x56, 0x53, 0xc7, 0x73, 0xa8, 0xcf,
	0x6f, 0xf2, 0x00, 0xb3, 0x81, 0xe4, 0x14, 0xda, 0x4b, 0x7f, 0xbd, 0xb8, 0xa5, 0xf3, 0xf1, 0xac,
	0xf7, 0x8c, 0x9c, 0xc1, 0xf3, 0xa5, 0xbf, 0xbe, 0xa6, 0xe3, 0xc5, 0xcd, 0xe7, 0xf5, 0x78, 0x32,
	0xff, 0xb2, 0xe8, 0x19, 0x05, 0xe8, 0x7d, 0xf3, 0xfc, 0xe9, 0xbc, 0x00, 0x6b, 0xe7, 0x1f, 0x01,
	0x4a, 0x33, 0x5a, 0xc6, 0x2b, 0x65, 0xf2, 0xf2, 0x13, 0xbd, 0x5d, 0x4d, 0x33, 0x81, 0x2e, 0xc0,
	0xd2, 0x5b, 0x4f, 0xa6, 0xb3, 0xa9, 0x3f, 0x9d, 0xf4, 0x6a, 0xd7, 0x97, 0xab, 0x8b, 0x2d, 0x53,
	0xbb, 0xfd, 0xdd, 0x70, 0xc3, 0x63, 0x37, 0x66, 0x09, 0x8a, 0x20, 0x12, 0x28, 0x5d, 0xfd, 0xa3,
	0x4b, 0x57, 0x8a, 0x8d, 0xbb, 0xe5, 0x6e, 0xb1, 0xf4, 0x5d, 0x53, 0xc3, 0x57, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x2c, 0x9e, 0x0b, 0x08, 0x15, 0x04, 0x00, 0x00,
}
